;; Copyright (c) 2013-2014 by Vijay Mathew Pandyalakal, All Rights Reserved.

(define (make-array dim fill constructor)
  (cond ((integer? dim)
         (if (procedure? fill)
             (let loop ((a (constructor dim))
                        (i 0))
               (cond ((< i dim)
                      (vector-set! a i (fill))
                      (loop a (+ i 1)))
                     (else a)))
             (constructor dim fill)))
        ((list? dim)
         (if (null? (cdr dim))
             (make-array (car dim) fill constructor)
             (make-array (car dim) (lambda () (make-array (cdr dim) fill constructor)) constructor)))
        (else (error "invalid array dimension. " dim))))

(define (array dim #!key fill) (make-array dim fill make-vector))

(define is_array vector?)

(define array_length vector-length)
(define array_at vector-ref)
(define array_set vector-set!)
(define array_to_list vector->list)
(define array_copy vector-copy)
(define subarray subvector)
(define array_append vector-append)
(define array_fill vector-fill!)
(define subarray_fill subvector-fill!)
(define subarray_move subvector-move!)
(define array_shrink vector-shrink!)

(define (array_sort arr #!key (test <) (type 'quick))
  (let ((s (sort (vector->list arr) test: test type: type))
        (len (vector-length arr)))
    (let loop ((s s) (i 0))
      (if (null? s) arr
          (begin (vector-set! arr i (car s))
                 (loop (cdr s) (+ i 1)))))))
    
(define (assert-vec-equal-lengths vec rest)
  (let ((len (vector-length vec)))
    (for-each (lambda (ls) 
                (if (not (eq? (vector-length vec) len))
                    (error (with-output-to-string 
                             "Vector is not of proper length: " 
                             (lambda () (slgn-display vec))))))
              rest)))

(define (vectors-ref vectors i)
  (map (lambda (v) (vector-ref v i)) vectors))

(define (vector-map1! f result vec len)
  (let loop ((i 0))
    (if (>= i len) 
        (if result result *void*)
        (let ((res (f (vector-ref vec i))))
          (if result (vector-set! result i res))
          (loop (+ i 1))))))

(define (vector-map2+! f result vecs len)
  (let loop ((i 0))
    (if (>= i len) 
        (if result result *void*)
        (let ((res (apply f (vectors-ref vecs i)))) 
          (if result (vector-set! result i res))
          (loop (+ i 1))))))

(define (vector-map f vec . vectors)
  (if (not (null? vectors))
      (assert-vec-equal-lengths vec vectors))
  (let ((len (vector-length vec)))
    (if (null? vectors)
        (vector-map1! f (make-vector len) vec len)
        (vector-map2+! f (make-vector len) (cons vec vectors) len))))

(define (vector-for-each f vec . vectors)
  (if (not (null? vectors))
      (assert-vec-equal-lengths vec vectors))
  (let ((len (vector-length vec)))
    (if (null? vectors)
        (vector-map1! f #f vec len)
        (vector-map2+! f #f (cons vec vectors) len))))

(define array_map vector-map)
(define array_for_each vector-for-each)

(define (array_index_of arr obj #!key (test *default-eq*))
  (let ((len (vector-length arr)))
    (let loop ((i 0))
      (cond ((>= i len) -1)
            ((test (vector-ref arr i) obj) i)
            (else (loop (+ i 1)))))))

(define arrays_ref vectors-ref)

;; byte arrays.

(define (byte_array dim #!key (fill 0)) (make-u8vector dim fill))
(define is_byte_array u8vector?)
(define byte_array_length u8vector-length)
(define byte_array_at u8vector-ref)
(define byte_array_set u8vector-set!)
(define byte_array_to_list u8vector->list)
(define list_to_byte_array list->u8vector)
(define byte_array_fill u8vector-fill!)
(define byte_subarray_fill subu8vector-fill!)
(define byte_array_append u8vector-append)
(define byte_array_copy u8vector-copy)
(define byte_subarray subu8vector)
(define byte_subarray_move subu8vector-move!)
(define byte_array_shrink u8vector-shrink!)
