;; Copyright (c) 2013-2014 by Vijay Mathew Pandyalakal, All Rights Reserved.

(define char_is_eq char=?)
(define char_is_lt char<?)
(define char_is_gt char>?)
(define char_is_lteq char<=?)
(define char_is_gteq char>=?)
(define is_char_ci_eq char-ci=?)
(define is_char_ci_lt char-ci<?)
(define is_char_ci_gt char-ci>?)
(define is_char_ci_lteq char-ci<=?)
(define is_char_ci_gteq char-ci>=?)

(define is_char char?)
(define is_char_alphabetic char-alphabetic?)
(define is_char_numeric char-numeric?)
(define is_char_whitespace char-whitespace?)
(define is_char_upper_case char-upper-case?)
(define is_char_lower_case char-lower-case?)
(define char_to_integer char->integer)
(define integer_to_char integer->char)
(define char_upcase char-upcase)
(define char_downcase char-downcase)
