;; Copyright (c) 2013-2014 by Vijay Mathew Pandyalakal, All Rights Reserved.

(define (stream type path-or-settings)
  ((case type
     ((file) open-file)
     ((array) open-vector)
     ((byte_array) open-u8vector)
     ((string) open-string)
     ((process) open-process)
     ((tcp_client) open-tcp-client)
     ((tcp_server) open-tcp-server)
     ((directory) open-directory)
     (else invalid-stream-type))
   (slgn-path/settings->scm-path/settings path-or-settings)))

(define (output_stream type path-or-settings)
  ((case type
     ((file) open-output-file)
     ((array) open-output-vector)
     ((byte_array) open-output-u8vector)
     ((string) open-output-string)
     ((process) open-output-process)
     ((tcp_client) open-tcp-client)
     ((tcp_server) open-tcp-server)
     ((directory) open-directory)
     (else invalid-stream-type))
   (slgn-path/settings->scm-path/settings path-or-settings)))

(define (input_stream type path-or-settings)
  ((case type
     ((file) open-input-file)
     ((array) open-input-vector)
     ((byte_array) open-input-u8vector)
     ((string) open-input-string)
     ((process) open-input-process)
     ((tcp_client) open-tcp-client)
     ((tcp_server) open-tcp-server)
     ((directory) open-directory)
     (else invalid-stream-type))
   (slgn-path/settings->scm-path/settings path-or-settings)))

(define (with_stream type path-or-settings fn)
  (let ((s (stream type path-or-settings)))
    (with-exception-catcher 
     (lambda (e)
       (if s (close-port s))
       (raise e))
     (lambda ()
       (let ((val (fn s)))
         (close-port s)
         (set! s #f)
         val)))))
    
(define (with_input_stream type path-or-settings fn)
  ((case type
     ((file) call-with-input-file)
     ((process) call-with-input-process)
     ((array) call-with-input-vector)
     ((byte_array) call-with-input-u8vector)
     ((string) call-with-input-string)
     (else invalid-stream-type))
   (slgn-path/settings->scm-path/settings path-or-settings)
   fn))

(define (with_output_stream type path-or-settings fn)
  ((case type
     ((file) call-with-output-file)
     ((process) call-with-output-process)
     ((array) call-with-output-vector)
     ((byte_array) call-with-output-u8vector)
     ((string) call-with-output-string)
     (else invalid-stream-type))
   (slgn-path/settings->scm-path/settings path-or-settings)
   fn))

(define (invalid-stream-type #!rest args)
  (error "not a supported stream type. " args))

(define process_pid process-pid)
(define process_status process-status)

(define (tcp_service_register path-or-settings fn) 
  (tcp-service-register! (slgn-path/settings->scm-path/settings path-or-settings) fn))

(define (tcp_service_unregister path-or-settings)
  (tcp-service-unregister! (slgn-path/settings->scm-path/settings path-or-settings)))

(define (close_stream port) 
  (if (port? port)
      (close-port port)))

(define is_input_stream input-port?)
(define is_output_stream output-port?)
(define is_stream port?)
(define current_input_stream current-input-port)
(define current_output_stream current-output-port)
(define close_input_stream close-input-port)
(define close_output_stream close-output-port)
(define read_char read-char)
(define peek_char peek-char)
(define is_char_ready char-ready?)
(define write_char write-char)
(define read_line read-line)
(define read_substring read-substring)
(define write_substring write-substring)
(define read_byte read-u8)
(define write_byte write-u8)
(define get_output_string get-output-string)
(define get_output_byte_array get-output-u8vector)
(define get_output_array get-output-vector)

(define (read_bytes bytes #!optional (start 0) end 
                    (port (current-input-port)) 
                    need)
  (if (not end) (set! end (u8vector-length bytes))) 
  (read-subu8vector bytes start end port need))

(define (write_bytes bytes #!optional (start 0) end 
                     (port (current-output-port)))
  (if (not end) (set! end (u8vector-length bytes)))
  (write-subu8vector bytes start end port))

(define flush_output force-output)
(define is_eos eof-object?)
(define input_stream_byte_position input-port-byte-position)
(define output_stream_byte_position output-port-byte-position)
(define scm_print print)
(define scm_println println)

(define (print #!key (to (current-output-port)) #!rest args)
  (let loop ((args args))
    (if (not (null? args))
        (begin (slgn-display (car args) display-string: #t port: to)
               (loop (cdr args))))))

(define (println #!key (to (current-output-port)) #!rest args)
  (apply print (append (list to: to) args))
  (newline to))

(define (write_expression obj #!optional (to (current-output-port)))
  (slgn-display obj port: to))

(define (make-delimited-tokenizer stream delimiters)
  (let ((current-token #f))
    (lambda (msg)
      (case msg
        ((next)
         (if (not current-token)
             (next-delimited-token stream delimiters)
             (let ((tmp current-token))
               (set! current-token #f)
               tmp)))
        ((peek)
         (if (not current-token)
             (set! current-token (next-delimited-token stream delimiters)))
         current-token)
        (else (error "Invalid message received by delimited-tokenizer. " msg))))))

(define (next-delimited-token stream delimiters)
  (if (eof-object? (peek-char stream))
      (read-char stream)
      (let ((cmpr (if (list? delimiters) memv char=?)))
        (let loop ((str '())
                   (c (peek-char stream)))
          (if (or (eof-object? c)
                  (cmpr c delimiters))
              (begin (read-char stream)
                     (list->string (reverse str)))
              (loop (cons (read-char stream) str) (peek-char stream)))))))

(define (stream_tokenizer stream #!key program
                          (delimiters #\space))
  (if program
      (make-tokenizer stream)
      (make-delimited-tokenizer stream delimiters)))

(define (peek_token tokenizer)
  (tokenizer 'peek))

(define (read_token tokenizer)
  (tokenizer 'next))

(define (tcp_server #!key (server_address "")
                    (port_number 0)
                    (backlog  128)
                    (reuse_address #t))
  (stream 'tcp_server `((server_address . ,server_address)
                        (port_number . ,port_number)
                        (backlog . ,backlog)
                        (reuse_address . ,reuse_address))))