#!/bin/bash

src_dir=$SLOGAN_ROOT/lib/media/c
src_files="$src_dir/core.c $src_dir/draw.c"
incs="-I$SLOGAN_ROOT/src/include -I$SLOGAN_ROOT/platform/gsc/include -I$src_dir"
out_file=$src_dir/media.so
unamestr=`uname`

if [[ "$unamestr" == 'Darwin' ]]; then
    incs="${incs} -I/Library/Frameworks/SDL2.framework/Headers -I/Library/Frameworks/SDL2_image.framework/Headers"
    gcc -dynamiclib $incs -Wl,-undefined -Wl,dynamic_lookup -o $out_file $src_files -framework SDL2 -framework SDL2_image
else # Linux and maybe BSDs?
    echo "The media library is not yet supported on this platform"
    exit 1
fi
