;; Copyright (c) 2013-2017 by Vijay Mathew Pandyalakal, All Rights Reserved.

(define core-compose compose)
(define core-identity identity)
(define core-compare compare)
(define core-mapfn mapfn)
(define core-partial partial)
(define core-complement complement)
(define core-apply apply)
(define core-not not)
(define core-until until)
(define core-map map)
(define core-for_each for_each)
(define core-for_all for_all)
(define core-exists exists)
(define core-fold_left fold_left)
(define core-fold_right fold_right)
(define core-fold fold)
(define core-callcc callcc)
(define core-dynamic_wind dynamic_wind)
(define core-values values)
(define core-call_with_values call_with_values)
(define core-force force)
(define core-eval eval)
(define core-is_eq is_eq)
(define core-is_eqv is_eqv)
(define core-is_equal is_equal)
(define core-is_boolean is_boolean)
(define core-is_empty is_empty)
(define core-is_pair is_pair)
(define core-is_number is_number)
(define core-is_complex is_complex)
(define core-is_real is_real)
(define core-is_rational is_rational)
(define core-is_integer is_integer)
(define core-is_char is_char)
(define core-is_string is_string)
(define core-is_array is_array)
(define core-is_u8array is_u8array)
(define core-is_s8array is_s8array)
(define core-is_bit_array is_bit_array)
(define core-is_symbol is_symbol)
(define core-is_hashtable is_hashtable)
(define core-is_function is_function)
(define core-pair pair)
(define core-head head)
(define core-tail tail)
(define core-car car)
(define core-cdr cdr)
(define core-set_head set_head)
(define core-set_tail set_tail)
(define core-list list)
(define core-list_of list_of)
(define core-list_set list_set)
(define core-is_list is_list)
(define core-length length)
(define core-count count)
(define core-at at)
(define core-list_tail list_tail)
(define core-drop drop)
(define core-take take)
(define core-take_while take_while)
(define core-drop_while drop_while)
(define core-append append)
(define core-reverse reverse)
(define core-memq memq)
(define core-memv memv)
(define core-member member)
(define core-memp memp)
(define core-remq remq)
(define core-remv remv)
(define core-remove remove)
(define core-remp remp)
(define core-filter filter)
(define core-partition partition)
(define core-sublist sublist)
(define core-range range)
(define core-find find)
(define core-position position)
(define core-assq assq)
(define core-assv assv)
(define core-assoc assoc)
(define core-assp assp)
(define core-get get)
(define core-copy_list copy_list)
(define core-zip zip)
(define core-unzip unzip)
(define core-zip_with zip_with)
(define core-sort sort)
(define core-quicksort quicksort)
(define core-mergesort mergesort)
(define core-first first)
(define core-rest rest)
(define core-nth nth)
(define core-nth_tail nth_tail)
(define core-second second)
(define core-third third)
(define core-fourth fourth)
(define core-fifth fifth)
(define core-sixth sixth)
(define core-seventh seventh)
(define core-eighth eighth)
(define core-ninth ninth)
(define core-tenth tenth)
(define core-accumulate accumulate)
(define core-enumerate enumerate)
(define core-is_exact is_exact)
(define core-is_inexact is_inexact)
(define core-number_is_eq number_is_eq)
(define core-number_is_lt number_is_lt)
(define core-number_is_gt number_is_gt)
(define core-number_is_lteq number_is_lteq)
(define core-number_is_gteq number_is_gteq)
(define core-add add)
(define core-sub sub)
(define core-mult mult)
(define core-div div)
(define core-inc inc)
(define core-dec dec)
(define core-is_zero is_zero)
(define core-is_positive is_positive)
(define core-is_negative is_negative)
(define core-is_even is_even)
(define core-is_odd is_odd)
(define core-is_prime is_prime)
(define core-is_finite is_finite)
(define core-is_infinite is_infinite)
(define core-is_nan is_nan)
(define core-quotient quotient)
(define core-remainder remainder)
(define core-modulo modulo)
(define core-quo quo)
(define core-rem rem)
(define core-mod mod)
(define core-truncate truncate)
(define core-floor floor)
(define core-ceiling ceiling)
(define core-round round)
(define core-abs abs)
(define core-max max)
(define core-min min)
(define core-gcd gcd)
(define core-lcm lcm)
(define core-expt expt)
(define core-inexact inexact)
(define core-exact exact)
(define core-rationalize rationalize)
(define core-numerator numerator)
(define core-denominator denominator)
(define core-rectangular rectangular)
(define core-polar polar)
(define core-real_part real_part)
(define core-imag_part imag_part)
(define core-angle angle)
(define core-magnitude magnitude)
(define core-sqrt sqrt)
(define core-exp exp)
(define core-log log)
(define core-logb logb)
(define core-sin sin)
(define core-cos cos)
(define core-tan tan)
(define core-asin asin)
(define core-acos acos)
(define core-atan atan)
(define core-bnot bnot)
(define core-band band)
(define core-bior bior)
(define core-bxor bxor)
(define core-bif bif)
(define core-bit_count bit_count)
(define core-blength blength)
(define core-first_bit_set first_bit_set)
(define core-is_bit_set is_bit_set)
(define core-is_any_bits_set is_any_bits_set)
(define core-is_all_bits_set is_all_bits_set)
(define core-copy_bit_field copy_bit_field)
(define core-bshift bshift)
(define core-rotate_bit_field rotate_bit_field)
(define core-reverse_bit_field reverse_bit_field)
(define core-string_to_number string_to_number)
(define core-number_to_string number_to_string)
(define core-is_fixnum is_fixnum)
(define core-least_fixnum least_fixnum)
(define core-greatest_fixnum greatest_fixnum)
(define core-fixnum_width fixnum_width)
(define core-fx_is_eq fx_is_eq)
(define core-fx_is_lt fx_is_lt)
(define core-fx_is_gt fx_is_gt)
(define core-fx_is_lteq fx_is_lteq)
(define core-fx_is_gteq fx_is_gteq)
(define core-fx_is_zero fx_is_zero)
(define core-fx_is_positive fx_is_positive)
(define core-fx_is_negative fx_is_negative)
(define core-fx_is_even fx_is_even)
(define core-fx_is_odd fx_is_odd)
(define core-fxmin fxmin)
(define core-fxmax fxmax)
(define core-fxadd fxadd)
(define core-fxsub fxsub)
(define core-fxmult fxmult)
(define core-fxdiv fxdiv)
(define core-fxmod fxmod)
(define core-fxadd_wrap fxadd_wrap)
(define core-fxsub_wrap fxsub_wrap)
(define core-fxmult_wrap fxmult_wrap)
(define core-fxnot fxnot)
(define core-fxand fxand)
(define core-fxior fxior)
(define core-fxxor fxxor)
(define core-fxif fxif)
(define core-fxbit_count fxbit_count)
(define core-fxlength fxlength)
(define core-fxfirst_bit_set fxfirst_bit_set)
(define core-fxbit_is_set fxbit_is_set)
(define core-fxshift fxshift)
(define core-fxshift_left fxshift_left)
(define core-fxshift_right fxshift_right)
(define core-fxshift_wrap fxshift_wrap)
(define core-fxshift_left_wrap fxshift_left_wrap)
(define core-fxshift_right_wrap fxshift_right_wrap)
(define core-fxlshift_right_wrap fxlshift_right_wrap)
(define core-is_flonum is_flonum)
(define core-fl_is_eq fl_is_eq)
(define core-fl_is_lt fl_is_lt)
(define core-fl_is_gt fl_is_gt)
(define core-fl_is_lteq fl_is_lteq)
(define core-fl_is_gteq fl_is_gteq)
(define core-fl_is_zero fl_is_zero)
(define core-fl_is_positive fl_is_positive)
(define core-fl_is_negative fl_is_negative)
(define core-fl_is_integer fl_is_integer)
(define core-fl_is_finite fl_is_finite)
(define core-fl_is_infinite fl_is_infinite)
(define core-fl_is_nan fl_is_nan)
(define core-fl_is_even fl_is_even)
(define core-fl_is_odd fl_is_odd)
(define core-flmin flmin)
(define core-flmax flmax)
(define core-fladd fladd)
(define core-flsub flsub)
(define core-flmult flmult)
(define core-fldiv fldiv)
(define core-flmod flmod)
(define core-flround flround)
(define core-fltruncate fltruncate)
(define core-flfloor flfloor)
(define core-flceiling flceiling)
(define core-flnumerator flnumerator)
(define core-fldenominator fldenominator)
(define core-flabs flabs)
(define core-flexp flexp)
(define core-fllog fllog)
(define core-fllogb fllogb)
(define core-flsin flsin)
(define core-flcos flcos)
(define core-fltan fltan)
(define core-flasin flasin)
(define core-flacos flacos)
(define core-flatan flatan)
(define core-flsqrt flsqrt)
(define core-flexpt flexpt)
(define core-fixnum_to_flonum fixnum_to_flonum)
(define core-inf inf)
(define core-_inf _inf)
(define core-nan nan)
(define core-zero zero)
(define core-_zero _zero)
(define core-random_integer random_integer)
(define core-random_real random_real)
(define core-random_byte_array random_byte_array)
(define core-default_random_source default_random_source)
(define core-random_source random_source)
(define core-is_random_source is_random_source)
(define core-random_source_state random_source_state)
(define core-random_source_set_state random_source_set_state)
(define core-random_source_randomize random_source_randomize)
(define core-random_source_pseudo_randomize random_source_pseudo_randomize)
(define core-random_source_for_integers random_source_for_integers)
(define core-random_source_for_reals random_source_for_reals)
(define core-random_source_for_byte_arrays random_source_for_byte_arrays)
(define core-char_is_eq char_is_eq)
(define core-char_is_lt char_is_lt)
(define core-char_is_gt char_is_gt)
(define core-char_is_lteq char_is_lteq)
(define core-char_is_gteq char_is_gteq)
(define core-char_is_ci_eq char_is_ci_eq)
(define core-char_is_ci_lt char_is_ci_lt)
(define core-char_is_ci_gt char_is_ci_gt)
(define core-char_is_ci_lteq char_is_ci_lteq)
(define core-char_is_ci_gteq char_is_ci_gteq)
(define core-char_is_alphabetic char_is_alphabetic)
(define core-char_is_numeric char_is_numeric)
(define core-char_is_whitespace char_is_whitespace)
(define core-char_is_lower_case char_is_lower_case)
(define core-char_is_upper_case char_is_upper_case)
(define core-char_downcase char_downcase)
(define core-char_upcase char_upcase)
(define core-char_to_integer char_to_integer)
(define core-integer_to_char integer_to_char)
(define core-string_is_eq string_is_eq)
(define core-string_is_lt string_is_lt)
(define core-string_is_gt string_is_gt)
(define core-string_is_lteq string_is_lteq)
(define core-string_is_gteq string_is_gteq)
(define core-string_is_ci_eq string_is_ci_eq)
(define core-string_is_ci_lt string_is_ci_lt)
(define core-string_is_ci_gt string_is_ci_gt)
(define core-string_is_ci_lteq string_is_ci_lteq)
(define core-string_is_ci_gteq string_is_ci_gteq)
(define core-string_starts_with string_starts_with)
(define core-string_ends_with string_ends_with)
(define core-string_ci_starts_with string_ci_starts_with)
(define core-string_ci_ends_with string_ci_ends_with)
(define core-string string)
(define core-make_string make_string)
(define core-string_length string_length)
(define core-string_at string_at)
(define core-string_set string_set)
(define core-strings_at strings_at)
(define core-string_index_of string_index_of)
(define core-string_replace_all string_replace_all)
(define core-string_copy string_copy)
(define core-string_append string_append)
(define core-substring substring)
(define core-string_fill string_fill)
(define core-string_upcase string_upcase)
(define core-string_downcase string_downcase)
(define core-string_titlecase string_titlecase)
(define core-string_ltrim string_ltrim)
(define core-string_rtrim string_rtrim)
(define core-string_trim string_trim)
(define core-string_map string_map)
(define core-string_for_each string_for_each)
(define core-string_split string_split)
(define core-strings_join strings_join)
(define core-string_to_list string_to_list)
(define core-list_to_string list_to_string)
(define core-string_to_u8array string_to_u8array)
(define core-to_string to_string)
(define core-u8array_to_string u8array_to_string)
(define core-u8array_to_bit_array u8array_to_bit_array)
(define core-string_to_symbol string_to_symbol)
(define core-symbol_to_string symbol_to_string)
(define core-gensym gensym)
(define core-is_true is_true)
(define core-is_false is_false)
(define core-void void)
(define core-is_void is_void)
(define core-is_object is_object)
(define core-array array)
(define core-make_array make_array)
(define core-array_length array_length)
(define core-array_at array_at)
(define core-array_ref array_ref)
(define core-array_ref_set array_ref_set)
(define core-arrays_at arrays_at)
(define core-array_set array_set)
(define core-array_fill array_fill)
(define core-array_to_list array_to_list)
(define core-list_to_array list_to_array)
(define core-array_copy array_copy)
(define core-array_append array_append)
(define core-array_shrink array_shrink)
(define core-subarray subarray)
(define core-subarray_fill subarray_fill)
(define core-subarray_move subarray_move)
(define core-array_map array_map)
(define core-array_for_each array_for_each)
(define core-u8array u8array)
(define core-s8array s8array)
(define core-make_u8array make_u8array)
(define core-make_s8array make_s8array)
(define core-u8array_length u8array_length)
(define core-s8array_length s8array_length)
(define core-u8array_at u8array_at)
(define core-s8array_at s8array_at)
(define core-u8array_set u8array_set)
(define core-s8array_set s8array_set)
(define core-u8array_to_list u8array_to_list)
(define core-s8array_to_list s8array_to_list)
(define core-list_to_u8array list_to_u8array)
(define core-list_to_s8array list_to_s8array)
(define core-object_to_u8array object_to_u8array)
(define core-u8array_to_object u8array_to_object)
(define core-u8array_fill u8array_fill)
(define core-s8array_fill s8array_fill)
(define core-u8array_append u8array_append)
(define core-s8array_append s8array_append)
(define core-u8array_copy u8array_copy)
(define core-s8array_copy s8array_copy)
(define core-u8array_shrink u8array_shrink)
(define core-s8array_shrink s8array_shrink)
(define core-subu8array subu8array)
(define core-subs8array subs8array)
(define core-subu8array_fill subu8array_fill)
(define core-subs8array_fill subs8array_fill)
(define core-subu8array_move subu8array_move)
(define core-subs8array_move subs8array_move)

(define core-is_s16array is_s16array)
(define core-s16array s16array)
(define core-make_s16array make_s16array)
(define core-s16array_length s16array_length)
(define core-s16array_at s16array_at)
(define core-s16array_set s16array_set)
(define core-s16array_to_list s16array_to_list)
(define core-list_to_s16array list_to_s16array)
(define core-s16array_fill s16array_fill)
(define core-s16array_append s16array_append)
(define core-s16array_copy s16array_copy)
(define core-s16array_shrink s16array_shrink)
(define core-subs16array subs16array)
(define core-subs16array_fill subs16array_fill)
(define core-subs16array_move subs16array_move)

(define core-is_s32array is_s32array)
(define core-s32array s32array)
(define core-make_s32array make_s32array)
(define core-s32array_length s32array_length)
(define core-s32array_at s32array_at)
(define core-s32array_set s32array_set)
(define core-s32array_to_list s32array_to_list)
(define core-list_to_s32array list_to_s32array)
(define core-s32array_fill s32array_fill)
(define core-s32array_append s32array_append)
(define core-s32array_copy s32array_copy)
(define core-s32array_shrink s32array_shrink)
(define core-subs32array subs32array)
(define core-subs32array_fill subs32array_fill)
(define core-subs32array_move subs32array_move)

(define core-is_u32array is_u32array)
(define core-u32array u32array)
(define core-make_u32array make_u32array)
(define core-u32array_length u32array_length)
(define core-u32array_at u32array_at)
(define core-u32array_set u32array_set)
(define core-u32array_to_list u32array_to_list)
(define core-list_to_u32array list_to_u32array)
(define core-u32array_fill u32array_fill)
(define core-u32array_append u32array_append)
(define core-u32array_copy u32array_copy)
(define core-u32array_shrink u32array_shrink)
(define core-subu32array subu32array)
(define core-subu32array_fill subu32array_fill)
(define core-subu32array_move subu32array_move)

(define core-is_u16array is_u16array)
(define core-u16array u16array)
(define core-make_u16array make_u16array)
(define core-u16array_length u16array_length)
(define core-u16array_at u16array_at)
(define core-u16array_set u16array_set)
(define core-u16array_to_list u16array_to_list)
(define core-list_to_u16array list_to_u16array)
(define core-u16array_fill u16array_fill)
(define core-u16array_append u16array_append)
(define core-u16array_copy u16array_copy)
(define core-u16array_shrink u16array_shrink)
(define core-subu16array subu16array)
(define core-subu16array_fill subu16array_fill)
(define core-subu16array_move subu16array_move)

(define core-is_s64array is_s64array)
(define core-s64array s64array)
(define core-make_s64array make_s64array)
(define core-s64array_length s64array_length)
(define core-s64array_at s64array_at)
(define core-s64array_set s64array_set)
(define core-s64array_to_list s64array_to_list)
(define core-list_to_s64array list_to_s64array)
(define core-s64array_fill s64array_fill)
(define core-s64array_append s64array_append)
(define core-s64array_copy s64array_copy)
(define core-s64array_shrink s64array_shrink)
(define core-subs64array subs64array)
(define core-subs64array_fill subs64array_fill)
(define core-subs64array_move subs64array_move)

(define core-is_u64array is_u64array)
(define core-u64array u64array)
(define core-make_u64array make_u64array)
(define core-u64array_length u64array_length)
(define core-u64array_at u64array_at)
(define core-u64array_set u64array_set)
(define core-u64array_to_list u64array_to_list)
(define core-list_to_u64array list_to_u64array)
(define core-u64array_fill u64array_fill)
(define core-u64array_append u64array_append)
(define core-u64array_copy u64array_copy)
(define core-u64array_shrink u64array_shrink)
(define core-subu64array subu64array)
(define core-subu64array_fill subu64array_fill)
(define core-subu64array_move subu64array_move)

(define core-is_f32array is_f32array)
(define core-f32array f32array)
(define core-make_f32array make_f32array)
(define core-f32array_length f32array_length)
(define core-f32array_at f32array_at)
(define core-f32array_set f32array_set)
(define core-f32array_to_list f32array_to_list)
(define core-list_to_f32array list_to_f32array)
(define core-f32array_fill f32array_fill)
(define core-f32array_append f32array_append)
(define core-f32array_copy f32array_copy)
(define core-f32array_shrink f32array_shrink)
(define core-subf32array subf32array)
(define core-subf32array_fill subf32array_fill)
(define core-subf32array_move subf32array_move)

(define core-is_f64array is_f64array)
(define core-f64array f64array)
(define core-make_f64array make_f64array)
(define core-f64array_length f64array_length)
(define core-f64array_at f64array_at)
(define core-f64array_set f64array_set)
(define core-f64array_to_list f64array_to_list)
(define core-list_to_f64array list_to_f64array)
(define core-f64array_fill f64array_fill)
(define core-f64array_append f64array_append)
(define core-f64array_copy f64array_copy)
(define core-f64array_shrink f64array_shrink)
(define core-subf64array subf64array)
(define core-subf64array_fill subf64array_fill)
(define core-subf64array_move subf64array_move)

(define core-is_bit_array is_bit_array)
(define core-bit_array bit_array)
(define core-make_bit_array make_bit_array)
(define core-bit_array_length bit_array_length)
(define core-bit_array_set bit_array_set)
(define core-bit_array_at bit_array_at)
(define core-bit_array_is_set bit_array_is_set)
(define core-bit_array_is_all_set bit_array_is_all_set)
(define core-bit_array_is_any_set bit_array_is_any_set)
(define core-bit_array_clear bit_array_clear)
(define core-bit_array_set_all bit_array_set_all)
(define core-bit_array_clear_all bit_array_clear_all)
(define core-bit_array_to_list bit_array_to_list)
(define core-list_to_bit_array list_to_bit_array)
(define core-bit_array_to_string bit_array_to_string)
(define core-string_to_bit_array string_to_bit_array)
(define core-bit_array_is_eq bit_array_is_eq)
(define core-bit_array_blit bit_array_blit)
(define core-bit_arrays_concat bit_arrays_concat)
(define core-subbitarray subbitarray)
(define core-make_hashtable make_hashtable)
(define core-make_eq_hashtable make_eq_hashtable)
(define core-make_eqv_hashtable make_eqv_hashtable)
(define core-make_equal_hashtable make_equal_hashtable)
(define core-is_hashtable is_hashtable)
(define core-eq_hash eq_hash)
(define core-eqv_hash eqv_hash)
(define core-equal_hash equal_hash)
(define core-string_hash string_hash)
(define core-symbol_hash symbol_hash)
(define core-string_ci_hash string_ci_hash)
(define core-hashtable_set hashtable_set)
(define core-hashtable_at hashtable_at)
(define core-hashtable_contains hashtable_contains)
(define core-hashtable_update hashtable_update)
(define core-hashtable_size hashtable_size)
(define core-hashtable_copy hashtable_copy)
(define core-hashtable_keys hashtable_keys)
(define core-hashtable_values hashtable_values)
(define core-hashtable_entries hashtable_entries)
(define core-hashtable_for_each hashtable_for_each)
(define core-transcoder transcoder)
(define core-transcoder_codec transcoder_codec)
(define core-transcoder_eol_style transcoder_eol_style)
(define core-transcoder_error_handling_mode transcoder_error_handling_mode)
(define core-file_reader file_reader)
(define core-file_writer file_writer)
(define core-file_stream file_stream)
(define core-current_reader current_reader)
(define core-current_writer current_writer)
(define core-current_error_stream current_error_stream)
(define core-byte_array_reader byte_array_reader)
(define core-byte_array_writer byte_array_writer)
(define core-get_output_bytes get_output_bytes)
(define core-string_reader string_reader)
(define core-string_writer string_writer)
(define core-get_output_string get_output_string)
(define core-pipe_reader pipe_reader)
(define core-pipe_writer pipe_writer)
(define core-pipe_stream pipe_stream)
(define core-pipe_process_pid pipe_process_pid)
(define core-pipe_process_status pipe_process_status)
(define core-tcp_server_stream tcp_server_stream)
(define core-tcp_client_stream tcp_client_stream)
(define core-is_stream is_stream)
(define core-is_writer is_writer)
(define core-is_reader is_reader)
(define core-close_stream close_stream)
(define core-close_writer close_writer)
(define core-close_reader close_reader)
(define core-stream_position stream_position)
(define core-stream_has_position stream_has_position)
(define core-set_stream_position set_stream_position)
(define core-call_with_stream call_with_stream)
(define core-is_eof_object is_eof_object)
(define core-eof_object eof_object)
(define core-read_byte read_byte)
(define core-read_n_bytes read_n_bytes)
(define core-read_all_bytes read_all_bytes)
(define core-read_char read_char)
(define core-peek_char peek_char)
(define core-read_n_chars read_n_chars)
(define core-read_all_chars read_all_chars)
(define core-read_line read_line)
(define core-read_all read_all)
(define core-read read)
(define core-write_byte write_byte)
(define core-write_bytes write_bytes)
(define core-write_n_bytes write_n_bytes)
(define core-write_char write_char)
(define core-write_chars write_chars)
(define core-write_n_chars write_n_chars)
(define core-show show)
(define core-showln showln)
(define core-display display)
(define core-print print)
(define core-println println)
(define core-newline newline)
(define core-write write)
(define core-flush_writer flush_writer)
(define core-reader_timeout reader_timeout)
(define core-writer_timeout writer_timeout)
(define core-stream_tokenizer stream_tokenizer)
(define core-get_token get_token)
(define core-peek_token peek_token)
(define core-is_keyword_token is_keyword_token)
(define core-is_special_token is_special_token)
(define core-is_valid_identifier is_valid_identifier)
(define core-special_token_to_string special_token_to_string)
(define core-expression expression)
(define core-statement statement)
(define core-slogan slogan)
(define core-is_task is_task)
(define core-task task)
(define core-root_task root_task)
(define core-self self)
(define core-task_run task_run)
(define core-task_yield task_yield)
(define core-task_sleep task_sleep)
(define core-task_terminate task_terminate)
(define core-task_join task_join)
(define core-task_name task_name)
(define core-task_set_data task_set_data)
(define core-task_data task_data)
(define core-task_set_base_priority task_set_base_priority)
(define core-task_base_priority task_base_priority)
(define core-task_set_priority_boost task_set_priority_boost)
(define core-task_priority_boost task_priority_boost)
(define core-task_base_priority task_base_priority)
(define core-task_set_quantum task_set_quantum)
(define core-task_quantum task_quantum)
(define core-task_send task_send)
(define core-task_receive task_receive)
(define core-task_messages_next task_messages_next)
(define core-task_messages_rewind task_messages_rewind)
(define core-task_state task_state)
(define core-task_state_is_uninitialized task_state_is_uninitialized)
(define core-task_state_is_initialized task_state_is_initialized)
(define core-task_state_is_active task_state_is_active)
(define core-task_state_active_waiting_for task_state_active_waiting_for)
(define core-task_state_active_timeout task_state_active_timeout)
(define core-task_state_is_normally_terminated task_state_is_normally_terminated)
(define core-task_state_normally_terminated_result task_state_normally_terminated_result)
(define core-task_state_is_abnormally_terminated task_state_is_abnormally_terminated)
(define core-task_state_abnormally_terminated_reason task_state_abnormally_terminated_reason)

(define core-task_group task_group)
(define core-is_task_group is_task_group)
(define core-task_group_name task_group_name)
(define core-task_group_parent task_group_parent)
(define core-task_group_resume task_group_resume)
(define core-task_group_suspend task_group_suspend)
(define core-task_group_terminate task_group_terminate)
(define core-mutex mutex)
(define core-is_mutex is_mutex)
(define core-mutex_name mutex_name)
(define core-mutex_set_data mutex_set_data)
(define core-mutex_data mutex_data)
(define core-mutex_state mutex_state)
(define core-mutex_lock mutex_lock)
(define core-mutex_unlock mutex_unlock)
(define core-monitor monitor)
(define core-is_monitor is_monitor)
(define core-monitor_name monitor_name)
(define core-monitor_set_data monitor_set_data)
(define core-monitor_data monitor_data)
(define core-monitor_notify monitor_notify)
(define core-monitor_broadcast monitor_broadcast)
(define core-rvar rvar)
(define core-rbind rbind)
(define core-rget rget)
(define core-process process)
(define core-process_send process_send)
(define core-process_receive process_receive)
(define core-process_close process_close)
(define core-current_directory current_directory)
(define core-path_expand path_expand)
(define core-path_normalize path_normalize)
(define core-path_extension path_extension)
(define core-path_strip_extension path_strip_extension)
(define core-path_directory path_directory)
(define core-path_strip_directory path_strip_directory)
(define core-path_strip_trailing_directory_separator path_strip_trailing_directory_separator)
(define core-path_volume path_volume)
(define core-path_strip_volume path_strip_volume)
(define core-create_directory create_directory)
(define core-create_link create_link)
(define core-create_symbolic_link create_symbolic_link)
(define core-rename_file rename_file)
(define core-copy_file copy_file)
(define core-delete_file delete_file)
(define core-delete_directory delete_directory)
(define core-list_directory list_directory)
(define core-file_exists file_exists)
(define core-file_info file_info)
(define core-is_file_info is_file_info)
(define core-file_info_type file_info_type)
(define core-file_info_device file_info_device)
(define core-file_info_inode file_info_inode)
(define core-file_info_mode file_info_mode)
(define core-file_info_number_of_links file_info_number_of_links)
(define core-file_info_owner file_info_owner)
(define core-file_info_group file_info_group)
(define core-file_info_size file_info_size)
(define core-file_info_last_access_time file_info_last_access_time)
(define core-file_info_last_modification_time file_info_last_modification_time)
(define core-file_info_last_change_time file_info_last_change_time)
(define core-file_info_creation_time file_info_creation_time)
(define core-file_info_attributes file_info_attributes)
(define core-file_type file_type)
(define core-file_device file_device)
(define core-file_inode file_inode)
(define core-file_mode file_mode)
(define core-file_number_of_links file_number_of_links)
(define core-file_owner file_owner)
(define core-file_group file_group)
(define core-file_size file_size)
(define core-file_last_access_time file_last_access_time)
(define core-file_last_modification_time file_last_modification_time)
(define core-file_last_change_time file_last_change_time)
(define core-file_creation_time file_creation_time)
(define core-file_attributes file_attributes)
(define core-os_name os_name)
(define core-host_name host_name)
(define core-host_info host_info)
(define core-is_host_info is_host_info)
(define core-host_info_name host_info_name)
(define core-host_info_aliases host_info_aliases)
(define core-host_info_addresses host_info_addresses)
(define core-shell_command shell_command)
(define core-exit exit)
(define core-command_line command_line)
(define core-getenv getenv)
(define core-setenv setenv)
(define core-compile compile)
(define core-load load)
(define core-reload reload)
(define core-link link)
(define core-now now)
(define core-now_utc now_utc)
(define core-now_seconds now_seconds)
(define core-string_to_time string_to_time)
(define core-time_to_string time_to_string)
(define core-process_times process_times)
(define core-real_time real_time)
(define core-cpu_time cpu_time)
(define core-current_exception_handler current_exception_handler)
(define core-set_current_exception_handler set_current_exception_handler)
(define core-raise raise)
(define core-abort abort)
(define core-is_noncontinuable_exception is_noncontinuable_exception)
(define core-noncontinuable_exception_reason noncontinuable_exception_reason)
(define core-show_exception show_exception)
(define core-error error)
(define core-is_error is_error)
(define core-error_message error_message)
(define core-error_args error_args)
(define core-c_struct_name c_struct_name)
(define core-c_struct_get c_struct_get)
(define core-c_struct_instance c_struct_instance)
(define core-pointer_to_c_struct pointer_to_c_struct)
(define core-ffi_open ffi_open)
(define core-ffi_close ffi_close)
(define core-ffi_fn ffi_fn)
(define core-ffi_call_void ffi_call_void)
(define core-ffi_call_void_pointer ffi_call_void_pointer)
(define core-ffi_call_char_string ffi_call_char_string)
(define core-ffi_call_int ffi_call_int)
(define core-ffi_call_uint ffi_call_uint)
(define core-ffi_call_int64 ffi_call_int64)
(define core-ffi_call_float ffi_call_float)
(define core-ffi_call_double ffi_call_double)
(define core-ffi_call_obj ffi_call_obj)
(define core-ffi_call_void_with_void_pointer ffi_call_void_with_void_pointer)
(define core-ffi_call_void_pointer_with_void_pointer ffi_call_void_pointer_with_void_pointer)
(define core-ffi_call_char_string_with_void_pointer ffi_call_char_string_with_void_pointer)
(define core-ffi_call_int_with_void_pointer ffi_call_int_with_void_pointer)
(define core-ffi_call_uint_with_void_pointer ffi_call_uint_with_void_pointer)
(define core-ffi_call_int64_with_void_pointer ffi_call_int64_with_void_pointer)
(define core-ffi_call_float_with_void_pointer ffi_call_float_with_void_pointer)
(define core-ffi_call_double_with_void_pointer ffi_call_double_with_void_pointer)
(define core-ffi_call_obj_with_void_pointer ffi_call_obj_with_void_pointer)
(define core-install_package install_package)
(define core-uninstall_package uninstall_package)
(define core-load_package load_package)
(define core-init_package init_package)

(define core-is_iterator is_iterator)
(define core-is_lpair is_lpair)
(define core-do_times do_times)
(define core-enable_asserts enable_asserts)
(define core-disable_asserts disable_asserts)
(define core-enable_function_contracts enable_function_contracts)
(define core-disable_function_contracts disable_function_contracts)

;; set functions
(define core-set_length set_length)
(define core-set_difference set_difference)
(define core-set_intersection set_intersection)
(define core-set_union set_union)
(define core-is_superset is_superset)
(define core-is_subset is_subset)
(define core-list_to_set list_to_set)
(define core-set_to_list set_to_list)
(define core-is_set is_set)
(define core-make_set make_set)
(define core-is_set_member is_set_member)
(define core-hashtable_to_set hashtable_to_set)
(define core-set set)

(define core-ref ref)
(define core-ref_set ref_set)
(define core-command_line_user_args command_line_user_args)

(define core-realize realize)
(define core-slogan_root slogan_root)
(define core-read_slogan_root read_slogan_root)
(define core-contains contains)

;; bit streams functions
(define core-bits_reader bits_reader)
(define core-bits_writer bits_writer)
(define core-read_bit read_bit)
(define core-read_bits read_bits)
(define core-bits_reader_align bits_reader_align)
(define core-bits_writer_flush bits_writer_flush)
(define core-write_bit write_bit)
(define core-write_bits write_bits)

;; meta-programming
(define core-compiler compiler)

(define (core *name*)
  (case *name*
    ((compose) core-compose)
    ((identity) core-identity)
    ((compare) core-compare)
    ((mapfn) core-mapfn)
    ((partial) core-partial)
    ((complement) core-complement)
    ((apply) core-apply)
    ((ref) core-ref)
    ((ref_set) core-ref_set)
    ((until) core-until)
    ((not) core-not)
    ((map) core-map)
    ((for_each) core-for_each)
    ((for_all) core-for_all)
    ((exists) core-exists)
    ((fold_left) core-fold_left)
    ((fold_right) core-fold_right)
    ((fold) core-fold)
    ((callcc) core-callcc)
    ((dynamic_wind) core-dynamic_wind)
    ((values) core-values)
    ((call_with_values) core-call_with_values)
    ((force) core-force)
    ((eval) core-eval)
    ((is_eq) core-is_eq)
    ((is_eqv) core-is_eqv)
    ((is_equal) core-is_equal)
    ((is_boolean) core-is_boolean)
    ((is_empty) core-is_empty)
    ((is_pair) core-is_pair)
    ((is_number) core-is_number)
    ((is_complex) core-is_complex)
    ((is_real) core-is_real)
    ((is_rational) core-is_rational)
    ((is_integer) core-is_integer)
    ((is_char) core-is_char)
    ((is_string) core-is_string)
    ((is_array) core-is_array)
    ((is_u8array) core-is_u8array)
    ((is_s8array) core-is_s8array)
    ((is_bit_array) core-is_bit_array)
    ((is_symbol) core-is_symbol)
    ((is_hashtable) core-is_hashtable)
    ((is_function) core-is_function)
    ((pair) core-pair)
    ((head) core-head)
    ((tail) core-tail)
    ((car) core-car)
    ((cdr) core-cdr)
    ((set_head) core-set_head)
    ((set_tail) core-set_tail)
    ((list) core-list)
    ((list_of) core-list_of)
    ((list_set) core-list_set)
    ((is_list) core-is_list)
    ((length) core-length)
    ((count) core-count)
    ((at) core-at)
    ((list_tail) core-list_tail)
    ((drop) core-drop)
    ((take) core-take)
    ((take_while) core-take_while)
    ((drop_while) core-drop_while)
    ((append) core-append)
    ((reverse) core-reverse)
    ((memq) core-memq)
    ((memv) core-memv)
    ((member) core-member)
    ((memp) core-memp)
    ((remq) core-remq)
    ((remv) core-remv)
    ((remove) core-remove)
    ((remp) core-remp)
    ((filter) core-filter)
    ((partition) core-partition)
    ((sublist) core-sublist)
    ((range) core-range)
    ((find) core-find)
    ((position) core-position)
    ((assq) core-assq)
    ((assv) core-assv)
    ((assoc) core-assoc)
    ((assp) core-assp)
    ((get) core-get)
    ((copy_list) core-copy_list)
    ((zip) core-zip)
    ((unzip) core-unzip)
    ((zip_with) core-zip_with)
    ((sort) core-sort)
    ((quicksort) core-quicksort)
    ((mergesort) core-mergesort)
    ((first) core-first)
    ((rest) core-rest)
    ((nth) core-nth)
    ((nth_tail) core-nth_tail)
    ((second) core-second)
    ((third) core-third)
    ((fourth) core-fourth)
    ((fifth) core-fifth)
    ((sixth) core-sixth)
    ((seventh) core-seventh)
    ((eighth) core-eighth)
    ((ninth) core-ninth)
    ((tenth) core-tenth)
    ((accumulate) core-accumulate)
    ((enumerate) core-enumerate)
    ((is_exact) core-is_exact)
    ((is_inexact) core-is_inexact)
    ((number_is_eq) core-number_is_eq)
    ((number_is_lt) core-number_is_lt)
    ((number_is_gt) core-number_is_gt)
    ((number_is_lteq) core-number_is_lteq)
    ((number_is_gteq) core-number_is_gteq)
    ((add) core-add)
    ((sub) core-sub)
    ((mult) core-mult)
    ((div) core-div)
    ((inc) core-inc)
    ((dec) core-dec)
    ((is_zero) core-is_zero)
    ((is_positive) core-is_positive)
    ((is_negative) core-is_negative)
    ((is_even) core-is_even)
    ((is_odd) core-is_odd)
    ((is_prime) core-is_prime)
    ((is_finite) core-is_finite)
    ((is_infinite) core-is_infinite)
    ((is_nan) core-is_nan)
    ((quotient) core-quotient)
    ((remainder) core-remainder)
    ((modulo) core-modulo)
    ((quo) core-quo)
    ((rem) core-rem)
    ((mod) core-mod)
    ((truncate) core-truncate)
    ((floor) core-floor)
    ((ceiling) core-ceiling)
    ((round) core-round)
    ((abs) core-abs)
    ((max) core-max)
    ((min) core-min)
    ((gcd) core-gcd)
    ((lcm) core-lcm)
    ((expt) core-expt)
    ((inexact) core-inexact)
    ((exact) core-exact)
    ((rationalize) core-rationalize)
    ((numerator) core-numerator)
    ((denominator) core-denominator)
    ((rectangular) core-rectangular)
    ((polar) core-polar)
    ((real_part) core-real_part)
    ((imag_part) core-imag_part)
    ((angle) core-angle)
    ((magnitude) core-magnitude)
    ((sqrt) core-sqrt)
    ((exp) core-exp)
    ((log) core-log)
    ((logb) core-logb)
    ((sin) core-sin)
    ((cos) core-cos)
    ((tan) core-tan)
    ((asin) core-asin)
    ((acos) core-acos)
    ((atan) core-atan)
    ((bnot) core-bnot)
    ((band) core-band)
    ((bior) core-bior)
    ((bxor) core-bxor)
    ((bif) core-bif)
    ((bit_count) core-bit_count)
    ((blength) core-blength)
    ((first_bit_set) core-first_bit_set)
    ((is_bit_set) core-is_bit_set)
    ((is_any_bits_set) core-is_any_bits_set)
    ((is_all_bits_set) core-is_all_bits_set)
    ((copy_bit_field) core-copy_bit_field)
    ((bshift) core-bshift)
    ((rotate_bit_field) core-rotate_bit_field)
    ((reverse_bit_field) core-reverse_bit_field)
    ((string_to_number) core-string_to_number)
    ((number_to_string) core-number_to_string)
    ((is_fixnum) core-is_fixnum)
    ((least_fixnum) core-least_fixnum)
    ((greatest_fixnum) core-greatest_fixnum)
    ((fixnum_width) core-fixnum_width)
    ((fx_is_eq) core-fx_is_eq)
    ((fx_is_lt) core-fx_is_lt)
    ((fx_is_gt) core-fx_is_gt)
    ((fx_is_lteq) core-fx_is_lteq)
    ((fx_is_gteq) core-fx_is_gteq)
    ((fx_is_zero) core-fx_is_zero)
    ((fx_is_positive) core-fx_is_positive)
    ((fx_is_negative) core-fx_is_negative)
    ((fx_is_even) core-fx_is_even)
    ((fx_is_odd) core-fx_is_odd)
    ((fxmin) core-fxmin)
    ((fxmax) core-fxmax)
    ((fxadd) core-fxadd)
    ((fxsub) core-fxsub)
    ((fxmult) core-fxmult)
    ((fxdiv) core-fxdiv)
    ((fxmod) core-fxmod)
    ((fxadd_wrap) core-fxadd_wrap)
    ((fxsub_wrap) core-fxsub_wrap)
    ((fxmult_wrap) core-fxmult_wrap)
    ((fxnot) core-fxnot)
    ((fxand) core-fxand)
    ((fxior) core-fxior)
    ((fxxor) core-fxxor)
    ((fxif) core-fxif)
    ((fxbit_count) core-fxbit_count)
    ((fxlength) core-fxlength)
    ((fxfirst_bit_set) core-fxfirst_bit_set)
    ((fxbit_is_set) core-fxbit_is_set)
    ((fxshift) core-fxshift)
    ((fxshift_left) core-fxshift_left)
    ((fxshift_right) core-fxshift_right)
    ((fxshift_wrap) core-fxshift_wrap)
    ((fxshift_left_wrap) core-fxshift_left_wrap)
    ((fxshift_right_wrap) core-fxshift_right_wrap)
    ((fxlshift_right_wrap) core-fxlshift_right_wrap)
    ((is_flonum) core-is_flonum)
    ((fl_is_eq) core-fl_is_eq)
    ((fl_is_lt) core-fl_is_lt)
    ((fl_is_gt) core-fl_is_gt)
    ((fl_is_lteq) core-fl_is_lteq)
    ((fl_is_gteq) core-fl_is_gteq)
    ((fl_is_zero) core-fl_is_zero)
    ((fl_is_positive) core-fl_is_positive)
    ((fl_is_negative) core-fl_is_negative)
    ((fl_is_integer) core-fl_is_integer)
    ((fl_is_finite) core-fl_is_finite)
    ((fl_is_infinite) core-fl_is_infinite)
    ((fl_is_nan) core-fl_is_nan)
    ((fl_is_even) core-fl_is_even)
    ((fl_is_odd) core-fl_is_odd)
    ((flmin) core-flmin)
    ((flmax) core-flmax)
    ((fladd) core-fladd)
    ((flsub) core-flsub)
    ((flmult) core-flmult)
    ((fldiv) core-fldiv)
    ((flmod) core-flmod)
    ((flround) core-flround)
    ((fltruncate) core-fltruncate)
    ((flfloor) core-flfloor)
    ((flceiling) core-flceiling)
    ((flnumerator) core-flnumerator)
    ((fldenominator) core-fldenominator)
    ((flabs) core-flabs)
    ((flexp) core-flexp)
    ((fllog) core-fllog)
    ((fllogb) core-fllogb)
    ((flsin) core-flsin)
    ((flcos) core-flcos)
    ((fltan) core-fltan)
    ((flasin) core-flasin)
    ((flacos) core-flacos)
    ((flatan) core-flatan)
    ((flsqrt) core-flsqrt)
    ((flexpt) core-flexpt)
    ((fixnum_to_flonum) core-fixnum_to_flonum)
    ((inf) core-inf)
    ((_inf) core-_inf)
    ((nan) core-nan)
    ((zero) core-zero)
    ((_zero) core-_zero)
    ((random_integer) core-random_integer)
    ((random_real) core-random_real)
    ((random_byte_array) core-random_byte_array)
    ((default_random_source) core-default_random_source)
    ((random_source) core-random_source)
    ((is_random_source) core-is_random_source)
    ((random_source_state) core-random_source_state)
    ((random_source_set_state) core-random_source_set_state)
    ((random_source_randomize) core-random_source_randomize)
    ((random_source_pseudo_randomize) core-random_source_pseudo_randomize)
    ((random_source_for_integers) core-random_source_for_integers)
    ((random_source_for_reals) core-random_source_for_reals)
    ((random_source_for_byte_arrays) core-random_source_for_byte_arrays)
    ((char_is_eq) core-char_is_eq)
    ((char_is_lt) core-char_is_lt)
    ((char_is_gt) core-char_is_gt)
    ((char_is_lteq) core-char_is_lteq)
    ((char_is_gteq) core-char_is_gteq)
    ((char_is_ci_eq) core-char_is_ci_eq)
    ((char_is_ci_lt) core-char_is_ci_lt)
    ((char_is_ci_gt) core-char_is_ci_gt)
    ((char_is_ci_lteq) core-char_is_ci_lteq)
    ((char_is_ci_gteq) core-char_is_ci_gteq)
    ((char_is_alphabetic) core-char_is_alphabetic)
    ((char_is_numeric) core-char_is_numeric)
    ((char_is_whitespace) core-char_is_whitespace)
    ((char_is_lower_case) core-char_is_lower_case)
    ((char_is_upper_case) core-char_is_upper_case)
    ((char_downcase) core-char_downcase)
    ((char_upcase) core-char_upcase)
    ((char_to_integer) core-char_to_integer)
    ((integer_to_char) core-integer_to_char)
    ((string_is_eq) core-string_is_eq)
    ((string_is_lt) core-string_is_lt)
    ((string_is_gt) core-string_is_gt)
    ((string_is_lteq) core-string_is_lteq)
    ((string_is_gteq) core-string_is_gteq)
    ((string_is_ci_eq) core-string_is_ci_eq)
    ((string_is_ci_lt) core-string_is_ci_lt)
    ((string_is_ci_gt) core-string_is_ci_gt)
    ((string_is_ci_lteq) core-string_is_ci_lteq)
    ((string_is_ci_gteq) core-string_is_ci_gteq)
    ((string_starts_with) core-string_starts_with)
    ((string_ends_with) core-string_ends_with)
    ((string_ci_starts_with) core-string_ci_starts_with)
    ((string_ci_ends_with) core-string_ci_ends_with)
    ((string) core-string)
    ((make_string) core-make_string)
    ((string_length) core-string_length)
    ((string_at) core-string_at)
    ((string_set) core-string_set)
    ((strings_at) core-strings_at)
    ((string_index_of) core-string_index_of)
    ((string_replace_all) core-string_replace_all)
    ((string_copy) core-string_copy)
    ((string_append) core-string_append)
    ((substring) core-substring)
    ((string_fill) core-string_fill)
    ((string_upcase) core-string_upcase)
    ((string_downcase) core-string_downcase)
    ((string_titlecase) core-string_titlecase)
    ((string_ltrim) core-string_ltrim)
    ((string_rtrim) core-string_rtrim)
    ((string_trim) core-string_trim)
    ((string_map) core-string_map)
    ((string_for_each) core-string_for_each)
    ((string_split) core-string_split)
    ((strings_join) core-strings_join)
    ((string_to_list) core-string_to_list)
    ((list_to_string) core-list_to_string)
    ((string_to_u8array) core-string_to_u8array)
    ((u8array_to_string) core-u8array_to_string)
    ((u8array_to_bit_array) core-u8array_to_bit_array)
    ((to_string) core-to_string)
    ((string_to_symbol) core-string_to_symbol)
    ((symbol_to_string) core-symbol_to_string)
    ((gensym) core-gensym)
    ((is_true) core-is_true)
    ((is_false) core-is_false)
    ((void) core-void)
    ((is_void) core-is_void)
    ((is_object) core-is_object)
    ((array) core-array)
    ((make_array) core-make_array)
    ((array_length) core-array_length)
    ((array_at) core-array_at)
    ((array_ref) core-array_ref)
    ((array_ref_set) core-array_ref_set)
    ((arrays_at) core-arrays_at)
    ((array_set) core-array_set)
    ((array_fill) core-array_fill)
    ((array_to_list) core-array_to_list)
    ((list_to_array) core-list_to_array)
    ((array_copy) core-array_copy)
    ((array_append) core-array_append)
    ((array_shrink) core-array_shrink)
    ((subarray) core-subarray)
    ((subarray_fill) core-subarray_fill)
    ((subarray_move) core-subarray_move)
    ((array_map) core-array_map)
    ((array_for_each) core-array_for_each)
    ((u8array) core-u8array)
    ((s8array) core-s8array)
    ((make_u8array) core-make_u8array)
    ((make_s8array) core-make_s8array)
    ((u8array_length) core-u8array_length)
    ((s8array_length) core-s8array_length)
    ((u8array_at) core-u8array_at)
    ((s8array_at) core-s8array_at)
    ((u8array_set) core-u8array_set)
    ((s8array_set) core-s8array_set)
    ((u8array_to_list) core-u8array_to_list)
    ((s8array_to_list) core-s8array_to_list)
    ((list_to_u8array) core-list_to_u8array)
    ((list_to_s8array) core-list_to_s8array)
    ((object_to_u8array) core-object_to_u8array)
    ((u8array_to_object) core-u8array_to_object)
    ((u8array_fill) core-u8array_fill)
    ((s8array_fill) core-s8array_fill)
    ((u8array_append) core-u8array_append)
    ((s8array_append) core-s8array_append)
    ((u8array_copy) core-u8array_copy)
    ((s8array_copy) core-s8array_copy)
    ((u8array_shrink) core-u8array_shrink)
    ((s8array_shrink) core-s8array_shrink)
    ((subu8array) core-subu8array)
    ((subs8array) core-subs8array)
    ((subu8array_fill) core-subu8array_fill)
    ((subs8array_fill) core-subs8array_fill)
    ((subu8array_move) core-subu8array_move)
    ((subs8array_move) core-subs8array_move)

    ((is_s16array) core-is_s16array)
    ((s16array) core-s16array)
    ((make_s16array) core-make_s16array)
    ((s16array_length) core-s16array_length)
    ((s16array_at) core-s16array_at)
    ((s16array_set) core-s16array_set)
    ((s16array_to_list) core-s16array_to_list)
    ((list_to_s16array) core-list_to_s16array)
    ((s16array_fill) core-s16array_fill)
    ((s16array_append) core-s16array_append)
    ((s16array_copy) core-s16array_copy)
    ((s16array_shrink) core-s16array_shrink)
    ((subs16array) core-subs16array)
    ((subs16array_fill) core-subs16array_fill)
    ((subs16array_move) core-subs16array_move)

    ((is_s32array) core-is_s32array)
    ((s32array) core-s32array)
    ((make_s32array) core-make_s32array)
    ((s32array_length) core-s32array_length)
    ((s32array_at) core-s32array_at)
    ((s32array_set) core-s32array_set)
    ((s32array_to_list) core-s32array_to_list)
    ((list_to_s32array) core-list_to_s32array)
    ((s32array_fill) core-s32array_fill)
    ((s32array_append) core-s32array_append)
    ((s32array_copy) core-s32array_copy)
    ((s32array_shrink) core-s32array_shrink)
    ((subs32array) core-subs32array)
    ((subs32array_fill) core-subs32array_fill)
    ((subs32array_move) core-subs32array_move)

    ((is_u32array) core-is_u32array)
    ((u32array) core-u32array)
    ((make_u32array) core-make_u32array)
    ((u32array_length) core-u32array_length)
    ((u32array_at) core-u32array_at)
    ((u32array_set) core-u32array_set)
    ((u32array_to_list) core-u32array_to_list)
    ((list_to_u32array) core-list_to_u32array)
    ((u32array_fill) core-u32array_fill)
    ((u32array_append) core-u32array_append)
    ((u32array_copy) core-u32array_copy)
    ((u32array_shrink) core-u32array_shrink)
    ((subu32array) core-subu32array)
    ((subu32array_fill) core-subu32array_fill)
    ((subu32array_move) core-subu32array_move)

    ((is_u16array) core-is_u16array)
    ((u16array) core-u16array)
    ((make_u16array) core-make_u16array)
    ((u16array_length) core-u16array_length)
    ((u16array_at) core-u16array_at)
    ((u16array_set) core-u16array_set)
    ((u16array_to_list) core-u16array_to_list)
    ((list_to_u16array) core-list_to_u16array)
    ((u16array_fill) core-u16array_fill)
    ((u16array_append) core-u16array_append)
    ((u16array_copy) core-u16array_copy)
    ((u16array_shrink) core-u16array_shrink)
    ((subu16array) core-subu16array)
    ((subu16array_fill) core-subu16array_fill)
    ((subu16array_move) core-subu16array_move)

    ((is_s64array) core-is_s64array)
    ((s64array) core-s64array)
    ((make_s64array) core-make_s64array)
    ((s64array_length) core-s64array_length)
    ((s64array_at) core-s64array_at)
    ((s64array_set) core-s64array_set)
    ((s64array_to_list) core-s64array_to_list)
    ((list_to_s64array) core-list_to_s64array)
    ((s64array_fill) core-s64array_fill)
    ((s64array_append) core-s64array_append)
    ((s64array_copy) core-s64array_copy)
    ((s64array_shrink) core-s64array_shrink)
    ((subs64array) core-subs64array)
    ((subs64array_fill) core-subs64array_fill)
    ((subs64array_move) core-subs64array_move)

    ((is_u64array) core-is_u64array)
    ((u64array) core-u64array)
    ((make_u64array) core-make_u64array)
    ((u64array_length) core-u64array_length)
    ((u64array_at) core-u64array_at)
    ((u64array_set) core-u64array_set)
    ((u64array_to_list) core-u64array_to_list)
    ((list_to_u64array) core-list_to_u64array)
    ((u64array_fill) core-u64array_fill)
    ((u64array_append) core-u64array_append)
    ((u64array_copy) core-u64array_copy)
    ((u64array_shrink) core-u64array_shrink)
    ((subu64array) core-subu64array)
    ((subu64array_fill) core-subu64array_fill)
    ((subu64array_move) core-subu64array_move)

    ((is_f32array) core-is_f32array)
    ((f32array) core-f32array)
    ((make_f32array) core-make_f32array)
    ((f32array_length) core-f32array_length)
    ((f32array_at) core-f32array_at)
    ((f32array_set) core-f32array_set)
    ((f32array_to_list) core-f32array_to_list)
    ((list_to_f32array) core-list_to_f32array)
    ((f32array_fill) core-f32array_fill)
    ((f32array_append) core-f32array_append)
    ((f32array_copy) core-f32array_copy)
    ((f32array_shrink) core-f32array_shrink)
    ((subf32array) core-subf32array)
    ((subf32array_fill) core-subf32array_fill)
    ((subf32array_move) core-subf32array_move)

    ((is_f64array) core-is_f64array)
    ((f64array) core-f64array)
    ((make_f64array) core-make_f64array)
    ((f64array_length) core-f64array_length)
    ((f64array_at) core-f64array_at)
    ((f64array_set) core-f64array_set)
    ((f64array_to_list) core-f64array_to_list)
    ((list_to_f64array) core-list_to_f64array)
    ((f64array_fill) core-f64array_fill)
    ((f64array_append) core-f64array_append)
    ((f64array_copy) core-f64array_copy)
    ((f64array_shrink) core-f64array_shrink)
    ((subf64array) core-subf64array)
    ((subf64array_fill) core-subf64array_fill)
    ((subf64array_move) core-subf64array_move)

    ((is_bit_array) core-is_bit_array)
    ((bit_array) core-bit_array)
    ((make_bit_array) core-make_bit_array)
    ((bit_array_length) core-bit_array_length)
    ((bit_array_set) core-bit_array_set)
    ((bit_array_at) core-bit_array_at)
    ((bit_array_is_set) core-bit_array_is_set)
    ((bit_array_is_all_set) core-bit_array_is_all_set)
    ((bit_array_is_any_set) core-bit_array_is_any_set)
    ((bit_array_clear) core-bit_array_clear)
    ((bit_array_set_all) core-bit_array_set_all)
    ((bit_array_clear_all) core-bit_array_clear_all)
    ((bit_array_to_list) core-bit_array_to_list)
    ((list_to_bit_array) core-list_to_bit_array)
    ((bit_array_to_string) core-bit_array_to_string)
    ((string_to_bit_array) core-string_to_bit_array)
    ((bit_array_is_eq) core-bit_array_is_eq)
    ((bit_array_blit) core-bit_array_blit)
    ((bit_arrays_concat) core-bit_arrays_concat)
    ((subbitarray) core-subbitarray)
    ((make_hashtable) core-make_hashtable)
    ((make_eq_hashtable) core-make_eq_hashtable)
    ((make_eqv_hashtable) core-make_eqv_hashtable)
    ((make_equal_hashtable) core-make_equal_hashtable)
    ((is_hashtable) core-is_hashtable)
    ((eq_hash) core-eq_hash)
    ((eqv_hash) core-eqv_hash)
    ((equal_hash) core-equal_hash)
    ((string_hash) core-string_hash)
    ((symbol_hash) core-symbol_hash)
    ((string_ci_hash) core-string_ci_hash)
    ((hashtable_set) core-hashtable_set)
    ((hashtable_at) core-hashtable_at)
    ((hashtable_contains) core-hashtable_contains)
    ((hashtable_update) core-hashtable_update)
    ((hashtable_size) core-hashtable_size)
    ((hashtable_copy) core-hashtable_copy)
    ((hashtable_keys) core-hashtable_keys)
    ((hashtable_values) core-hashtable_values)
    ((hashtable_entries) core-hashtable_entries)
    ((hashtable_for_each) core-hashtable_for_each)
    ((transcoder) core-transcoder)
    ((transcoder_codec) core-transcoder_codec)
    ((transcoder_eol_style) core-transcoder_eol_style)
    ((transcoder_error_handling_mode) core-transcoder_error_handling_mode)
    ((file_reader) core-file_reader)
    ((file_writer) core-file_writer)
    ((file_stream) core-file_stream)
    ((current_reader) core-current_reader)
    ((current_writer) core-current_writer)
    ((current_error_stream) core-current_error_stream)
    ((byte_array_reader) core-byte_array_reader)
    ((byte_array_writer) core-byte_array_writer)
    ((get_output_bytes) core-get_output_bytes)
    ((string_reader) core-string_reader)
    ((string_writer) core-string_writer)
    ((get_output_string) core-get_output_string)
    ((pipe_reader) core-pipe_reader)
    ((pipe_writer) core-pipe_writer)
    ((pipe_stream) core-pipe_stream)
    ((pipe_process_pid) core-pipe_process_pid)
    ((pipe_process_status) core-pipe_process_status)
    ((tcp_server_stream) core-tcp_server_stream)
    ((tcp_client_stream) core-tcp_client_stream)
    ((is_stream) core-is_stream)
    ((is_writer) core-is_writer)
    ((is_reader) core-is_reader)
    ((close_stream) core-close_stream)
    ((close_writer) core-close_writer)
    ((close_reader) core-close_reader)
    ((stream_position) core-stream_position)
    ((stream_has_position) core-stream_has_position)
    ((set_stream_position) core-set_stream_position)
    ((call_with_stream) core-call_with_stream)
    ((is_eof_object) core-is_eof_object)
    ((eof_object) core-eof_object)
    ((read_byte) core-read_byte)
    ((read_n_bytes) core-read_n_bytes)
    ((read_all_bytes) core-read_all_bytes)
    ((read_char) core-read_char)
    ((peek_char) core-peek_char)
    ((read_n_chars) core-read_n_chars)
    ((read_all_chars) core-read_all_chars)
    ((read_line) core-read_line)
    ((read_all) core-read_all)
    ((read) core-read)
    ((write_byte) core-write_byte)
    ((write_bytes) core-write_bytes)
    ((write_n_bytes) core-write_n_bytes)
    ((write_char) core-write_char)
    ((write_chars) core-write_chars)
    ((write_n_chars) core-write_n_chars)
    ((show) core-show)
    ((showln) core-showln)
    ((display) core-display)
    ((print) core-print)
    ((println) core-println)
    ((newline) core-newline)
    ((write) core-write)
    ((flush_writer) core-flush_writer)
    ((reader_timeout) core-reader_timeout)
    ((writer_timeout) core-writer_timeout)
    ((stream_tokenizer) core-stream_tokenizer)
    ((get_token) core-get_token)
    ((peek_token) core-peek_token)
    ((is_keyword_token) core-is_keyword_token)
    ((is_special_token) core-is_special_token)
    ((is_valid_identifier) core-is_valid_identifier)
    ((special_token_to_string) core-special_token_to_string)
    ((expression) core-expression)
    ((statement) core-statement)
    ((slogan) core-slogan)
    ((bits_reader) core-bits_reader)
    ((bits_writer) core-bits_writer)
    ((read_bit) core-read_bit)
    ((read_bits) core-read_bits)
    ((bits_reader_align) core-bits_reader_align)
    ((bits_writer_flush) core-bits_writer_flush)
    ((write_bit) core-write_bit)
    ((write_bits) core-write_bits)
    ((is_task) core-is_task)
    ((task) core-task)
    ((root_task) core-root_task)
    ((self) core-self)
    ((task_run) core-task_run)
    ((task_yield) core-task_yield)
    ((task_sleep) core-task_sleep)
    ((task_terminate) core-task_terminate)
    ((task_join) core-task_join)
    ((task_name) core-task_name)
    ((task_set_data) core-task_set_data)
    ((task_data) core-task_data)
    ((task_set_base_priority) core-task_set_base_priority)
    ((task_base_priority) core-task_base_priority)
    ((task_set_priority_boost) core-task_set_priority_boost)
    ((task_priority_boost) core-task_priority_boost)
    ((task_base_priority) core-task_base_priority)
    ((task_set_quantum) core-task_set_quantum)
    ((task_quantum) core-task_quantum)
    ((task_send) core-task_send)
    ((task_receive) core-task_receive)
    ((task_messages_next) core-task_messages_next)
    ((task_messages_rewind) core-task_messages_rewind)
    ((task_state) core-task_state)
    ((task_state_is_uninitialized) core-task_state_is_uninitialized)
    ((task_state_is_initialized) core-task_state_is_initialized)
    ((task_state_is_active) core-task_state_is_active)
    ((task_state_active_waiting_for) core-task_state_active_waiting_for)
    ((task_state_active_timeout) core-task_state_active_timeout)
    ((task_state_is_normally_terminated) core-task_state_is_normally_terminated)
    ((task_state_normally_terminated_result) core-task_state_normally_terminated_result)
    ((task_state_is_abnormally_terminated) core-task_state_is_abnormally_terminated)
    ((task_state_abnormally_terminated_reason) core-task_state_abnormally_terminated_reason)

    ((task_group) core-task_group)
    ((is_task_group) core-is_task_group)
    ((task_group_name) core-task_group_name)
    ((task_group_parent) core-task_group_parent)
    ((task_group_resume) core-task_group_resume)
    ((task_group_suspend) core-task_group_suspend)
    ((task_group_terminate) core-task_group_terminate)
    ((mutex) core-mutex)
    ((is_mutex) core-is_mutex)
    ((mutex_name) core-mutex_name)
    ((mutex_set_data) core-mutex_set_data)
    ((mutex_data) core-mutex_data)
    ((mutex_state) core-mutex_state)
    ((mutex_lock) core-mutex_lock)
    ((mutex_unlock) core-mutex_unlock)
    ((monitor) core-monitor)
    ((is_monitor) core-is_monitor)
    ((monitor_name) core-monitor_name)
    ((monitor_set_data) core-monitor_set_data)
    ((monitor_data) core-monitor_data)
    ((monitor_notify) core-monitor_notify)
    ((monitor_broadcast) core-monitor_broadcast)
    ((rvar) core-rvar)
    ((rbind) core-rbind)
    ((rget) core-rget)
    ((process) core-process)
    ((process_send) core-process_send)
    ((process_receive) core-process_receive)
    ((process_close) core-process_close)
    ((current_directory) core-current_directory)
    ((path_expand) core-path_expand)
    ((path_normalize) core-path_normalize)
    ((path_extension) core-path_extension)
    ((path_strip_extension) core-path_strip_extension)
    ((path_directory) core-path_directory)
    ((path_strip_directory) core-path_strip_directory)
    ((path_strip_trailing_directory_separator) core-path_strip_trailing_directory_separator)
    ((path_volume) core-path_volume)
    ((path_strip_volume) core-path_strip_volume)
    ((create_directory) core-create_directory)
    ((create_link) core-create_link)
    ((create_symbolic_link) core-create_symbolic_link)
    ((rename_file) core-rename_file)
    ((copy_file) core-copy_file)
    ((delete_file) core-delete_file)
    ((delete_directory) core-delete_directory)
    ((list_directory) core-list_directory)
    ((file_exists) core-file_exists)
    ((file_info) core-file_info)
    ((is_file_info) core-is_file_info)
    ((file_info_type) core-file_info_type)
    ((file_info_device) core-file_info_device)
    ((file_info_inode) core-file_info_inode)
    ((file_info_mode) core-file_info_mode)
    ((file_info_number_of_links) core-file_info_number_of_links)
    ((file_info_owner) core-file_info_owner)
    ((file_info_group) core-file_info_group)
    ((file_info_size) core-file_info_size)
    ((file_info_last_access_time) core-file_info_last_access_time)
    ((file_info_last_modification_time) core-file_info_last_modification_time)
    ((file_info_last_change_time) core-file_info_last_change_time)
    ((file_info_creation_time) core-file_info_creation_time)
    ((file_info_attributes) core-file_info_attributes)
    ((file_type) core-file_type)
    ((file_device) core-file_device)
    ((file_inode) core-file_inode)
    ((file_mode) core-file_mode)
    ((file_number_of_links) core-file_number_of_links)
    ((file_owner) core-file_owner)
    ((file_group) core-file_group)
    ((file_size) core-file_size)
    ((file_last_access_time) core-file_last_access_time)
    ((file_last_modification_time) core-file_last_modification_time)
    ((file_last_change_time) core-file_last_change_time)
    ((file_creation_time) core-file_creation_time)
    ((file_attributes) core-file_attributes)
    ((os_name) core-os_name)
    ((host_name) core-host_name)
    ((host_info) core-host_info)
    ((is_host_info) core-is_host_info)
    ((host_info_name) core-host_info_name)
    ((host_info_aliases) core-host_info_aliases)
    ((host_info_addresses) core-host_info_addresses)
    ((shell_command) core-shell_command)
    ((exit) core-exit)
    ((command_line) core-command_line)
    ((getenv) core-getenv)
    ((setenv) core-setenv)
    ((compile) core-compile)
    ((load) core-load)
    ((reload) core-reload)
    ((link) core-link)
    ((now) core-now)
    ((now_utc) core-now_utc)
    ((now_seconds) core-now_seconds)
    ((string_to_time) core-string_to_time)
    ((time_to_string) core-time_to_string)
    ((process_times) core-process_times)
    ((real_time) core-real_time)
    ((cpu_time) core-cpu_time)
    ((current_exception_handler) core-current_exception_handler)
    ((set_current_exception_handler) core-set_current_exception_handler)
    ((raise) core-raise)
    ((abort) core-abort)
    ((is_noncontinuable_exception) core-is_noncontinuable_exception)
    ((noncontinuable_exception_reason) core-noncontinuable_exception_reason)
    ((show_exception) core-show_exception)
    ((error) core-error)
    ((is_error) core-is_error)
    ((error_message) core-error_message)
    ((error_args) core-error_args)
    ((c_struct_name) core-c_struct_name)
    ((c_struct_get) core-c_struct_get)
    ((c_struct_instance) core-c_struct_instance)
    ((pointer_to_c_struct) core-pointer_to_c_struct)
    ((ffi_open) core-ffi_open)
    ((ffi_close) core-ffi_close)
    ((ffi_fn) core-ffi_fn)
    ((ffi_call_void) core-ffi_call_void)
    ((ffi_call_void_pointer) core-ffi_call_void_pointer)
    ((ffi_call_char_string) core-ffi_call_char_string)
    ((ffi_call_int) core-ffi_call_int)
    ((ffi_call_uint) core-ffi_call_uint)
    ((ffi_call_int64) core-ffi_call_int64)
    ((ffi_call_float) core-ffi_call_float)
    ((ffi_call_double) core-ffi_call_double)
    ((ffi_call_obj) core-ffi_call_obj)
    ((ffi_call_void_with_void_pointer) core-ffi_call_void_with_void_pointer)
    ((ffi_call_void_pointer_with_void_pointer) core-ffi_call_void_pointer_with_void_pointer)
    ((ffi_call_char_string_with_void_pointer) core-ffi_call_char_string_with_void_pointer)
    ((ffi_call_int_with_void_pointer) core-ffi_call_int_with_void_pointer)
    ((ffi_call_uint_with_void_pointer) core-ffi_call_uint_with_void_pointer)
    ((ffi_call_int64_with_void_pointer) core-ffi_call_int64_with_void_pointer)
    ((ffi_call_float_with_void_pointer) core-ffi_call_float_with_void_pointer)
    ((ffi_call_double_with_void_pointer) core-ffi_call_double_with_void_pointer)
    ((ffi_call_obj_with_void_pointer) core-ffi_call_obj_with_void_pointer)
    ((install_package) core-install_package)
    ((uninstall_package) core-uninstall_package)
    ((load_package) core-load_package)
    ((init_package) core-init_package)

    ((is_iterator) core-is_iterator)
    ((is_lpair) core-is_lpair)
    ((do_times) core-do_times)
    ((enable_asserts) core-enable_asserts)
    ((disable_asserts) core-disable_asserts)
    ((enable_function_contracts) core-enable_function_contracts)
    ((disable_function_contracts) core-disable_function_contracts)

    ((command_line_user_args) core-command_line_user_args)

    ;; set functions
    ((set_length) core-set_length)
    ((set_difference) core-set_difference)
    ((set_intersection) core-set_intersection)
    ((set_union) core-set_union)
    ((is_superset) core-is_superset)
    ((is_subset) core-is_subset)
    ((list_to_set) core-list_to_set)
    ((set_to_list) core-set_to_list)
    ((is_set) core-is_set)
    ((make_set) core-make_set)
    ((is_set_member) core-is_set_member)
    ((hashtable_to_set) core-hashtable_to_set)
    ((set) core-set)
    ((realize) core-realize)
    ((slogan_root) core-slogan_root)
    ((read_slogan_root) core-read_slogan_root)
    ((contains) core-contains)
    ((compiler) core-compiler)
    (else (scm-error "Binding not found" *name*))))

(define *core-names* '(_inf _zero abort abs accumulate acos add angle append
                            apply array array_append array_at array_copy array_fill
                            array_for_each array_length array_map array_ref
                            array_ref_set array_set array_shrink
                            array_to_list arrays_at asin assoc assp assq assv at atan
                            band bif bior bit_array bit_array_at bit_array_blit
                            bit_array_clear bit_array_clear_all bit_array_is_all_set
                            bit_array_is_any_set bit_array_is_eq bit_array_is_set
                            bit_array_length bit_array_set bit_array_set_all
                            bit_array_to_list bit_array_to_string bit_arrays_concat
                            bit_count bits_reader bits_writer read_bit read_bits
                            bits_reader_align bits_writer_flush write_bit write_bits
                            blength bnot bshift bxor byte_array_reader
                            byte_array_writer c_struct_get c_struct_instance
                            c_struct_name call_with_stream call_with_values callcc car
                            cdr ceiling char_downcase char_is_alphabetic char_is_ci_eq
                            char_is_ci_gt char_is_ci_gteq char_is_ci_lt char_is_ci_lteq
                            char_is_eq char_is_gt char_is_gteq char_is_lower_case
                            char_is_lt char_is_lteq char_is_numeric char_is_upper_case
                            char_is_whitespace char_to_integer char_upcase close_reader
                            close_stream close_writer command_line contains
                            command_line_user_args compare compile compiler complement
                            compose copy_bit_field copy_file copy_list cos count cpu_time
                            create_directory create_link create_symbolic_link
                            current_directory current_error_stream
                            current_exception_handler current_reader
                            current_writer dec default_random_source delete_directory
                            delete_file denominator disable_asserts display div do_times
                            drop drop_while dynamic_wind eighth enable_asserts enumerate
                            eof_object eq_hash equal_hash eqv_hash error error_args
                            error_message eval exact exists exit exp expression expt
                            f32array f32array_append f32array_at f32array_copy
                            f32array_fill f32array_length f32array_set f32array_shrink
                            f32array_to_list f64array f64array_append f64array_at
                            f64array_copy f64array_fill f64array_length f64array_set
                            f64array_shrink f64array_to_list ffi_call_char_string
                            ffi_call_char_string_with_void_pointer ffi_call_double
                            ffi_call_double_with_void_pointer ffi_call_float
                            ffi_call_float_with_void_pointer ffi_call_int ffi_call_int64
                            ffi_call_int64_with_void_pointer
                            ffi_call_int_with_void_pointer ffi_call_obj
                            ffi_call_obj_with_void_pointer ffi_call_uint
                            ffi_call_uint_with_void_pointer ffi_call_void
                            ffi_call_void_pointer
                            ffi_call_void_pointer_with_void_pointer
                            ffi_call_void_with_void_pointer ffi_close ffi_fn ffi_open
                            fifth file_attributes file_creation_time file_device
                            file_exists file_group file_info file_info_attributes
                            file_info_creation_time file_info_device file_info_group
                            file_info_inode file_info_last_access_time
                            file_info_last_change_time file_info_last_modification_time
                            file_info_mode file_info_number_of_links file_info_owner
                            file_info_size file_info_type file_inode
                            file_last_access_time file_last_change_time
                            file_last_modification_time file_mode file_number_of_links
                            file_owner file_reader file_size file_stream file_type
                            file_writer filter find first first_bit_set fixnum_to_flonum
                            fixnum_width fl_is_eq fl_is_even fl_is_finite fl_is_gt
                            fl_is_gteq fl_is_infinite fl_is_integer fl_is_lt fl_is_lteq
                            fl_is_nan fl_is_negative fl_is_odd fl_is_positive fl_is_zero
                            flabs flacos fladd flasin flatan flceiling flcos
                            fldenominator fldiv flexp flexpt flfloor fllog fllogb flmax
                            flmin flmod flmult flnumerator floor flround flsin flsqrt
                            flsub fltan fltruncate flush_writer fold fold_left
                            fold_right for_all for_each force fourth fx_is_eq fx_is_even
                            fx_is_gt fx_is_gteq fx_is_lt fx_is_lteq fx_is_negative
                            fx_is_odd fx_is_positive fx_is_zero fxadd fxadd_wrap fxand
                            fxbit_count fxbit_is_set fxdiv fxfirst_bit_set fxif fxior
                            fxlength fxlshift_right_wrap fxmax fxmin fxmod fxmult
                            fxmult_wrap fxnot fxshift fxshift_left fxshift_left_wrap
                            fxshift_right fxshift_right_wrap fxshift_wrap fxsub
                            fxsub_wrap fxxor gcd gensym get get_output_bytes
                            get_output_string get_token getenv greatest_fixnum
                            hashtable_at hashtable_contains hashtable_copy
                            hashtable_entries hashtable_for_each hashtable_keys
                            hashtable_set hashtable_size hashtable_to_set
                            hashtable_update hashtable_values head host_info
                            host_info_addresses host_info_aliases host_info_name
                            host_name identity imag_part inc inexact inf init_package
                            install_package integer_to_char is_all_bits_set
                            is_any_bits_set is_array is_bit_array is_bit_array
                            is_bit_set is_boolean is_char is_complex is_empty
                            is_eof_object is_eq is_equal is_eqv is_error is_even
                            is_exact is_f32array is_f64array is_false is_file_info
                            is_finite is_fixnum is_flonum is_function is_hashtable
                            is_hashtable is_host_info is_inexact is_infinite is_integer
                            is_iterator is_keyword_token is_list is_lpair is_monitor
                            is_mutex is_nan is_negative is_noncontinuable_exception
                            is_number is_object is_odd is_pair is_positive is_prime
                            is_random_source is_rational is_reader is_real is_s16array
                            is_s32array is_s64array is_s8array is_set is_set_member
                            is_special_token is_stream is_string is_subset is_superset
                            is_symbol is_task is_task_group is_true is_u16array
                            is_u32array is_u64array is_u8array is_void is_writer is_zero
                            is_valid_identifier lcm least_fixnum length link list list_directory
                            list_of list_set list_tail list_to_array list_to_bit_array list_to_f32array
                            list_to_f64array list_to_s16array list_to_s32array
                            list_to_s64array list_to_s8array list_to_set list_to_string
                            list_to_u16array list_to_u32array list_to_u64array
                            list_to_u8array load load_package log logb magnitude
                            make_array make_bit_array make_eq_hashtable
                            make_equal_hashtable make_eqv_hashtable make_f32array
                            make_f64array make_hashtable make_s16array make_s32array
                            make_s64array make_s8array make_set make_string
                            make_u16array make_u32array make_u64array make_u8array map
                            mapfn max member memp memq memv mergesort min mod modulo
                            monitor monitor_broadcast monitor_data monitor_name
                            monitor_notify monitor_set_data mult mutex mutex_data
                            mutex_lock mutex_name mutex_set_data mutex_state
                            mutex_unlock nan newline ninth
                            noncontinuable_exception_reason now now_seconds now_utc nth
                            not nth_tail number_is_eq number_is_gt number_is_gteq
                            number_is_lt number_is_lteq number_to_string numerator
                            object_to_u8array os_name pair partial partition
                            path_directory path_expand path_extension path_normalize
                            path_strip_directory path_strip_extension
                            path_strip_trailing_directory_separator path_strip_volume
                            path_volume peek_char peek_token pipe_process_pid
                            pipe_process_status pipe_reader pipe_stream pipe_writer
                            pointer_to_c_struct polar position print println process
                            process_close process_receive process_send process_times
                            quicksort quo quotient raise random_byte_array
                            random_integer random_real random_source
                            random_source_for_byte_arrays random_source_for_integers
                            random_source_for_reals random_source_pseudo_randomize
                            random_source_randomize random_source_set_state
                            random_source_state range rationalize rbind read
                            read_all read_all_bytes read_all_chars read_byte read_char
                            read_line read_n_bytes read_n_chars reader_timeout real_part
                            real_time realize rectangular ref ref_set reload rem remainder
                            remove remp remq remv rename_file rest reverse read_slogan_root
                            reverse_bit_field rget root_task rotate_bit_field round rvar
                            s16array s16array_append s16array_at s16array_copy
                            s16array_fill s16array_length s16array_set s16array_shrink
                            s16array_to_list s32array s32array_append s32array_at
                            s32array_copy s32array_fill s32array_length s32array_set
                            s32array_shrink s32array_to_list s64array s64array_append
                            s64array_at s64array_copy s64array_fill s64array_length
                            s64array_set s64array_shrink s64array_to_list s8array
                            s8array_append s8array_at s8array_copy s8array_fill
                            s8array_length s8array_set s8array_shrink s8array_to_list
                            second self set set_current_exception_handler set_difference
                            set_head set_intersection set_length set_stream_position
                            set_tail set_to_list set_union setenv seventh shell_command
                            show show_exception showln sin sixth slogan slogan_root sort
                            special_token_to_string sqrt statement stream_has_position
                            stream_position stream_tokenizer string string_append
                            string_at string_ci_ends_with string_ci_hash
                            string_ci_starts_with string_copy string_downcase
                            string_ends_with string_fill string_for_each string_hash
                            string_index_of string_is_ci_eq string_is_ci_gt
                            string_is_ci_gteq string_is_ci_lt string_is_ci_lteq
                            string_is_eq string_is_gt string_is_gteq string_is_lt
                            string_is_lteq string_length string_ltrim string_map
                            string_reader string_replace_all string_rtrim string_set
                            string_split string_starts_with string_titlecase
                            string_to_bit_array string_to_list string_to_number
                            string_to_symbol string_to_time string_to_u8array
                            string_trim string_upcase string_writer strings_at
                            strings_join sub subarray subarray_fill subarray_move
                            subbitarray subf32array subf32array_fill subf32array_move
                            subf64array subf64array_fill subf64array_move sublist
                            subs16array subs16array_fill subs16array_move subs32array
                            subs32array_fill subs32array_move subs64array
                            subs64array_fill subs64array_move subs8array subs8array_fill
                            subs8array_move substring subu16array subu16array_fill
                            subu16array_move subu32array subu32array_fill
                            subu32array_move subu64array subu64array_fill
                            subu64array_move subu8array subu8array_fill subu8array_move
                            symbol_hash symbol_to_string tail take take_while tan task
                            task_base_priority task_base_priority task_data task_group
                            task_group_name task_group_parent task_group_resume
                            task_group_suspend task_group_terminate task_join
                            task_messages_next task_messages_rewind task_name
                            task_priority_boost task_quantum task_receive task_run
                            task_send task_set_base_priority task_set_data
                            task_set_priority_boost task_set_quantum task_sleep
                            task_state task_state_abnormally_terminated_reason
                            task_state_active_timeout task_state_active_waiting_for
                            task_state_is_abnormally_terminated task_state_is_active
                            task_state_is_initialized task_state_is_normally_terminated
                            task_state_is_uninitialized
                            task_state_normally_terminated_result task_terminate
                            task_yield tcp_client_stream tcp_server_stream tenth third
                            time_to_string to_string transcoder transcoder_codec
                            transcoder_eol_style transcoder_error_handling_mode truncate
                            u16array u16array_append u16array_at u16array_copy
                            u16array_fill u16array_length u16array_set u16array_shrink
                            u16array_to_list u32array u32array_append u32array_at
                            u32array_copy u32array_fill u32array_length u32array_set
                            u32array_shrink u32array_to_list u64array u64array_append
                            u64array_at u64array_copy u64array_fill u64array_length
                            u64array_set u64array_shrink u64array_to_list u8array
                            u8array_append u8array_at u8array_copy u8array_fill
                            u8array_length u8array_set u8array_shrink
                            u8array_to_bit_array u8array_to_list u8array_to_object
                            u8array_to_string uninstall_package until unzip values void
                            write write_byte write_bytes write_char write_chars
                            write_n_bytes write_n_chars writer_timeout zero zip
                            zip_with))

(define (core-name? name) (scm-memq name *core-names*))
