;; Copyright (c) 2013-2016 by Vijay Mathew Pandyalakal, All Rights Reserved.

(define core_compose compose)
(define core_identiy identity)
(define core_mapfn mapfn)
(define core_partial partial)
(define core_complement complement)
(define core_namespace_names namespace_names)
(define core_namespace_hide namespace_hide)
(define core_namespace_unhide namespace_unhide)
(define core_namespace_create namespace_create)
(define core_namespace_delete namespace_delete)
(define core_apply apply)
(define core_until until)
(define core_map map)
(define core_for_each for_each)
(define core_for_all for_all)
(define core_exists exists)
(define core_fold_left fold_left)
(define core_fold_right fold_right)
(define core_fold fold)
(define core_callcc callcc)
(define core_dynamic_wind dynamic_wind)
(define core_values values)
(define core_call_with_values call_with_values)
(define core_force force)
(define core_eval eval)
(define core_is_eq is_eq)
(define core_is_eqv is_eqv)
(define core_is_equal is_equal)
(define core_is_boolean is_boolean)
(define core_is_empty is_empty)
(define core_is_pair is_pair)
(define core_is_number is_number)
(define core_is_complex is_complex)
(define core_is_real is_real)
(define core_is_rational is_rational)
(define core_is_integer is_integer)
(define core_is_char is_char)
(define core_is_string is_string)
(define core_is_array is_array)
(define core_is_u8array is_u8array)
(define core_is_s8array is_s8array)
(define core_is_bit_array is_bit_array)
(define core_is_symbol is_symbol)
(define core_is_hashtable is_hashtable)
(define core_is_function is_function)
(define core_pair pair)
(define core_head head)
(define core_tail tail)
(define core_set_head set_head)
(define core_set_tail set_tail)
(define core_list list)
(define core_list_of list_of)
(define core_is_list is_list)
(define core_length length)
(define core_at at)
(define core_list_tail list_tail)
(define core_drop drop)
(define core_take take)
(define core_take_while take_while)
(define core_drop_while drop_while)
(define core_append append)
(define core_reverse reverse)
(define core_memq memq)
(define core_memv memv)
(define core_member member)
(define core_memp memp)
(define core_remq remq)
(define core_remv remv)
(define core_remove remove)
(define core_remp remp)
(define core_filter filter)
(define core_partition partition)
(define core_sublist sublist)
(define core_range range)
(define core_find find)
(define core_position position)
(define core_assq assq)
(define core_assv assv)
(define core_assoc assoc)
(define core_assp assp)
(define core_get get)
(define core_copy_list copy_list)
(define core_zip zip)
(define core_zip_with zip_with)
(define core_sort sort)
(define core_quicksort quicksort)
(define core_mergesort mergesort)
(define core_first first)
(define core_rest rest)
(define core_nth nth)
(define core_nth_tail nth_tail)
(define core_second second)
(define core_third third)
(define core_fourth fourth)
(define core_fifth fifth)
(define core_sixth sixth)
(define core_seventh seventh)
(define core_eighth eighth)
(define core_ninth ninth)
(define core_tenth tenth)
(define core_accumulate accumulate)
(define core_enumerate enumerate)
(define core_is_exact is_exact)
(define core_is_inexact is_inexact)
(define core_number_is_eq number_is_eq)
(define core_number_is_lt number_is_lt)
(define core_number_is_gt number_is_gt)
(define core_number_is_lteq number_is_lteq)
(define core_number_is_gteq number_is_gteq)
(define core_add add)
(define core_sub sub)
(define core_mult mult)
(define core_div div)
(define core_inc inc)
(define core_dec dec)
(define core_is_zero is_zero)
(define core_is_positive is_positive)
(define core_is_negative is_negative)
(define core_is_even is_even)
(define core_is_odd is_odd)
(define core_is_prime is_prime)
(define core_is_finite is_finite)
(define core_is_infinite is_infinite)
(define core_is_nan is_nan)
(define core_quotient quotient)
(define core_remainder remainder)
(define core_modulo modulo)
(define core_quo quo)
(define core_rem rem)
(define core_mod mod)
(define core_truncate truncate)
(define core_floor floor)
(define core_ceiling ceiling)
(define core_round round)
(define core_abs abs)
(define core_max max)
(define core_min min)
(define core_gcd gcd)
(define core_lcm lcm)
(define core_expt expt)
(define core_inexact inexact)
(define core_exact exact)
(define core_rationalize rationalize)
(define core_numerator numerator)
(define core_denominator denominator)
(define core_rectangular rectangular)
(define core_polar polar)
(define core_real_part real_part)
(define core_imag_part imag_part)
(define core_angle angle)
(define core_magnitude magnitude)
(define core_sqrt sqrt)
(define core_exp exp)
(define core_log log)
(define core_logb logb)
(define core_sin sin)
(define core_cos cos)
(define core_tan tan)
(define core_asin asin)
(define core_acos acos)
(define core_atan atan)
(define core_bitwise_not bitwise_not)
(define core_bitwise_and bitwise_and)
(define core_bitwise_ior bitwise_ior)
(define core_bitwise_xor bitwise_xor)
(define core_bitwise_if bitwise_if)
(define core_bitwise_bit_count bitwise_bit_count)
(define core_bitwise_length bitwise_length)
(define core_bitwise_first_bit_set bitwise_first_bit_set)
(define core_bitwise_is_bit_set bitwise_is_bit_set)
(define core_bitwise_is_any_bits_set bitwise_is_any_bits_set)
(define core_bitwise_is_all_bits_set bitwise_is_all_bits_set)
(define core_bitwise_copy_bit_field bitwise_copy_bit_field)
(define core_bitwise_arithmetic_shift bitwise_arithmetic_shift)
(define core_bitwise_rotate_bit_field bitwise_rotate_bit_field)
(define core_bitwise_reverse_bit_field bitwise_reverse_bit_field)
(define core_string_to_number string_to_number)
(define core_number_to_string number_to_string)
(define core_is_fixnum is_fixnum)
(define core_least_fixnum least_fixnum)
(define core_greatest_fixnum greatest_fixnum)
(define core_fixnum_width fixnum_width)
(define core_fx_is_eq fx_is_eq)
(define core_fx_is_lt fx_is_lt)
(define core_fx_is_gt fx_is_gt)
(define core_fx_is_lteq fx_is_lteq)
(define core_fx_is_gteq fx_is_gteq)
(define core_fx_is_zero fx_is_zero)
(define core_fx_is_positive fx_is_positive)
(define core_fx_is_negative fx_is_negative)
(define core_fx_is_even fx_is_even)
(define core_fx_is_odd fx_is_odd)      
(define core_fxmin fxmin)
(define core_fxmax fxmax)
(define core_fxadd fxadd)
(define core_fxsub fxsub)
(define core_fxmult fxmult)
(define core_fxdiv fxdiv)
(define core_fxmod fxmod)
(define core_fxadd_wrap fxadd_wrap)
(define core_fxsub_wrap fxsub_wrap)
(define core_fxmult_wrap fxmult_wrap)
(define core_fxnot fxnot)
(define core_fxand fxand)
(define core_fxior fxior)
(define core_fxxor fxxor)
(define core_fxif fxif)
(define core_fxbit_count fxbit_count)
(define core_fxlength fxlength)
(define core_fxfirst_bit_set fxfirst_bit_set)
(define core_fxbit_is_set fxbit_is_set)
(define core_fxarithmetic_shift fxarithmetic_shift)
(define core_fxarithmetic_shift_left fxarithmetic_shift_left)
(define core_fxarithmetic_shift_right fxarithmetic_shift_right)
(define core_fxarithmetic_shift_wrap fxarithmetic_shift_wrap)
(define core_fxarithmetic_shift_left_wrap fxarithmetic_shift_left_wrap)
(define core_fxarithmetic_shift_right_wrap fxarithmetic_shift_right_wrap)
(define core_fxlogical_shift_right_wrap fxlogical_shift_right_wrap)
(define core_is_flonum is_flonum)
(define core_fl_is_eq fl_is_eq)
(define core_fl_is_lt fl_is_lt)
(define core_fl_is_gt fl_is_gt)
(define core_fl_is_lteq fl_is_lteq)
(define core_fl_is_gteq fl_is_gteq)
(define core_fl_is_zero fl_is_zero)
(define core_fl_is_positive fl_is_positive)
(define core_fl_is_negative fl_is_negative)
(define core_fl_is_integer fl_is_integer)
(define core_fl_is_finite fl_is_finite)
(define core_fl_is_infinite fl_is_infinite)
(define core_fl_is_nan fl_is_nan)
(define core_fl_is_even fl_is_even)
(define core_fl_is_odd fl_is_odd)
(define core_flmin flmin)
(define core_flmax flmax)
(define core_fladd fladd)
(define core_flsub flsub)
(define core_flmult flmult)
(define core_fldiv fldiv)
(define core_flmod flmod)
(define core_flround flround)
(define core_fltruncate fltruncate)
(define core_flfloor flfloor)
(define core_flceiling flceiling)
(define core_flnumerator flnumerator)
(define core_fldenominator fldenominator)
(define core_flabs flabs)
(define core_flexp flexp)
(define core_fllog fllog)
(define core_fllogb fllogb)
(define core_flsin flsin)
(define core_flcos flcos)
(define core_fltan fltan)
(define core_flasin flasin)
(define core_flacos flacos)
(define core_flatan flatan)
(define core_flsqrt flsqrt)
(define core_flexpt flexpt)
(define core_fixnum_to_flonum fixnum_to_flonum)
(define core_inf inf)
(define core__inf _inf)
(define core_nan nan)
(define core_zero zero)
(define core__zero _zero)
(define core_random_integer random_integer)
(define core_random_real random_real)
(define core_random_byte_array random_byte_array)
(define core_default_random_source default_random_source)
(define core_random_source random_source)
(define core_is_random_source is_random_source)
(define core_random_source_state random_source_state)
(define core_random_source_set_state random_source_set_state)
(define core_random_source_randomize random_source_randomize)
(define core_random_source_pseudo_randomize random_source_pseudo_randomize)
(define core_random_source_for_integers random_source_for_integers)
(define core_random_source_for_reals random_source_for_reals)
(define core_random_source_for_byte_arrays random_source_for_byte_arrays)
(define core_char_is_eq char_is_eq)
(define core_char_is_lt char_is_lt)
(define core_char_is_gt char_is_gt)
(define core_char_is_lteq char_is_lteq)
(define core_char_is_gteq char_is_gteq)
(define core_char_is_ci_eq char_is_ci_eq)
(define core_char_is_ci_lt char_is_ci_lt)
(define core_char_is_ci_gt char_is_ci_gt)
(define core_char_is_ci_lteq char_is_ci_lteq)
(define core_char_is_ci_gteq char_is_ci_gteq)
(define core_char_is_alphabetic char_is_alphabetic)
(define core_char_is_numeric char_is_numeric)
(define core_char_is_whitespace char_is_whitespace)
(define core_char_is_lower_case char_is_lower_case)
(define core_char_is_upper_case char_is_upper_case)
(define core_char_downcase char_downcase)
(define core_char_upcase char_upcase)
(define core_char_to_integer char_to_integer)
(define core_integer_to_char integer_to_char)
(define core_string_is_eq string_is_eq)
(define core_string_is_lt string_is_lt)
(define core_string_is_gt string_is_gt)
(define core_string_is_lteq string_is_lteq)
(define core_string_is_gteq string_is_gteq)
(define core_string_is_ci_eq string_is_ci_eq)
(define core_string_is_ci_lt string_is_ci_lt)
(define core_string_is_ci_gt string_is_ci_gt)
(define core_string_is_ci_lteq string_is_ci_lteq)
(define core_string_is_ci_gteq string_is_ci_gteq)
(define core_string_starts_with string_starts_with)
(define core_string_ends_with string_ends_with)
(define core_string_ci_starts_with string_ci_starts_with)
(define core_string_ci_ends_with string_ci_ends_with)
(define core_string string)
(define core_make_string make_string)
(define core_string_length string_length)
(define core_string_at string_at)
(define core_string_set string_set)
(define core_strings_at strings_at)
(define core_string_index_of string_index_of)
(define core_string_replace_all string_replace_all)
(define core_string_copy string_copy)
(define core_string_append string_append)
(define core_substring substring)
(define core_string_fill string_fill)
(define core_string_upcase string_upcase)
(define core_string_downcase string_downcase)
(define core_string_titlecase string_titlecase)
(define core_string_ltrim string_ltrim)
(define core_string_rtrim string_rtrim)
(define core_string_trim string_trim)
(define core_string_map string_map)
(define core_string_for_each string_for_each)
(define core_string_split string_split)
(define core_strings_join strings_join)
(define core_string_to_list string_to_list)
(define core_list_to_string list_to_string)
(define core_string_to_u8array string_to_u8array)
(define core_u8array_to_string u8array_to_string)
(define core_u8array_to_bit_array u8array_to_bit_array)
(define core_string_to_symbol string_to_symbol)
(define core_symbol_to_string symbol_to_string)
(define core_gensym gensym)
(define core_is_true is_true)
(define core_is_false is_false)
(define core_void void)
(define core_is_void is_void)
(define core_is_object is_object)
(define core_array array)
(define core_make_array make_array)
(define core_array_length array_length)
(define core_array_at array_at)
(define core_arrays_at arrays_at)
(define core_array_set array_set)
(define core_array_fill array_fill)
(define core_array_to_list array_to_list)
(define core_list_to_array list_to_array)
(define core_array_copy array_copy)
(define core_array_append array_append)
(define core_array_shrink array_shrink)
(define core_subarray subarray)
(define core_subarray_fill subarray_fill)
(define core_subarray_move subarray_move)
(define core_array_sort array_sort)
(define core_array_map array_map)
(define core_array_for_each array_for_each)
(define core_u8array u8array)
(define core_s8array s8array)
(define core_make_u8array make_u8array)
(define core_make_s8array make_s8array)
(define core_u8array_length u8array_length)
(define core_s8array_length s8array_length)
(define core_u8array_at u8array_at)
(define core_s8array_at s8array_at)
(define core_u8array_set u8array_set)
(define core_s8array_set s8array_set)
(define core_u8array_to_list u8array_to_list)
(define core_s8array_to_list s8array_to_list)
(define core_list_to_u8array list_to_u8array)
(define core_list_to_s8array list_to_s8array)
(define core_object_to_u8array object_to_u8array)
(define core_u8array_to_object u8array_to_object)
(define core_u8array_fill u8array_fill)
(define core_s8array_fill s8array_fill)
(define core_u8array_append u8array_append)
(define core_s8array_append s8array_append)
(define core_u8array_copy u8array_copy)
(define core_s8array_copy s8array_copy)
(define core_u8array_shrink u8array_shrink)
(define core_s8array_shrink s8array_shrink)
(define core_subu8array subu8array)
(define core_subs8array subs8array)
(define core_subu8array_fill subu8array_fill)
(define core_subs8array_fill subs8array_fill)
(define core_subu8array_move subu8array_move)
(define core_subs8array_move subs8array_move)

(define core_is_s16array is_s16array)
(define core_s16array s16array)
(define core_make_s16array make_s16array)
(define core_s16array_length s16array_length)
(define core_s16array_at s16array_at)
(define core_s16array_set s16array_set)
(define core_s16array_to_list s16array_to_list)
(define core_list_to_s16array list_to_s16array)
(define core_s16array_fill s16array_fill)
(define core_s16array_append s16array_append)
(define core_s16array_copy s16array_copy)
(define core_s16array_shrink s16array_shrink)
(define core_subs16array subs16array)
(define core_subs16array_fill subs16array_fill)
(define core_subs16array_move subs16array_move)

(define core_is_s32array is_s32array)
(define core_s32array s32array)
(define core_make_s32array make_s32array)
(define core_s32array_length s32array_length)
(define core_s32array_at s32array_at)
(define core_s32array_set s32array_set)
(define core_s32array_to_list s32array_to_list)
(define core_list_to_s32array list_to_s32array)
(define core_s32array_fill s32array_fill)
(define core_s32array_append s32array_append)
(define core_s32array_copy s32array_copy)
(define core_s32array_shrink s32array_shrink)
(define core_subs32array subs32array)
(define core_subs32array_fill subs32array_fill)
(define core_subs32array_move subs32array_move)

(define core_is_u32array is_u32array)
(define core_u32array u32array)
(define core_make_u32array make_u32array)
(define core_u32array_length u32array_length)
(define core_u32array_at u32array_at)
(define core_u32array_set u32array_set)
(define core_u32array_to_list u32array_to_list)
(define core_list_to_u32array list_to_u32array)
(define core_u32array_fill u32array_fill)
(define core_u32array_append u32array_append)
(define core_u32array_copy u32array_copy)
(define core_u32array_shrink u32array_shrink)
(define core_subu32array subu32array)
(define core_subu32array_fill subu32array_fill)
(define core_subu32array_move subu32array_move)

(define core_is_u16array is_u16array)
(define core_u16array u16array)
(define core_make_u16array make_u16array)
(define core_u16array_length u16array_length)
(define core_u16array_at u16array_at)
(define core_u16array_set u16array_set)
(define core_u16array_to_list u16array_to_list)
(define core_list_to_u16array list_to_u16array)
(define core_u16array_fill u16array_fill)
(define core_u16array_append u16array_append)
(define core_u16array_copy u16array_copy)
(define core_u16array_shrink u16array_shrink)
(define core_subu16array subu16array)
(define core_subu16array_fill subu16array_fill)
(define core_subu16array_move subu16array_move)

(define core_is_s64array is_s64array)
(define core_s64array s64array)
(define core_make_s64array make_s64array)
(define core_s64array_length s64array_length)
(define core_s64array_at s64array_at)
(define core_s64array_set s64array_set)
(define core_s64array_to_list s64array_to_list)
(define core_list_to_s64array list_to_s64array)
(define core_s64array_fill s64array_fill)
(define core_s64array_append s64array_append)
(define core_s64array_copy s64array_copy)
(define core_s64array_shrink s64array_shrink)
(define core_subs64array subs64array)
(define core_subs64array_fill subs64array_fill)
(define core_subs64array_move subs64array_move)

(define core_is_u64array is_u64array)
(define core_u64array u64array)
(define core_make_u64array make_u64array)
(define core_u64array_length u64array_length)
(define core_u64array_at u64array_at)
(define core_u64array_set u64array_set)
(define core_u64array_to_list u64array_to_list)
(define core_list_to_u64array list_to_u64array)
(define core_u64array_fill u64array_fill)
(define core_u64array_append u64array_append)
(define core_u64array_copy u64array_copy)
(define core_u64array_shrink u64array_shrink)
(define core_subu64array subu64array)
(define core_subu64array_fill subu64array_fill)
(define core_subu64array_move subu64array_move)

(define core_is_f32array is_f32array)
(define core_f32array f32array)
(define core_make_f32array make_f32array)
(define core_f32array_length f32array_length)
(define core_f32array_at f32array_at)
(define core_f32array_set f32array_set)
(define core_f32array_to_list f32array_to_list)
(define core_list_to_f32array list_to_f32array)
(define core_f32array_fill f32array_fill)
(define core_f32array_append f32array_append)
(define core_f32array_copy f32array_copy)
(define core_f32array_shrink f32array_shrink)
(define core_subf32array subf32array)
(define core_subf32array_fill subf32array_fill)
(define core_subf32array_move subf32array_move)

(define core_is_f64array is_f64array)
(define core_f64array f64array)
(define core_make_f64array make_f64array)
(define core_f64array_length f64array_length)
(define core_f64array_at f64array_at)
(define core_f64array_set f64array_set)
(define core_f64array_to_list f64array_to_list)
(define core_list_to_f64array list_to_f64array)
(define core_f64array_fill f64array_fill)
(define core_f64array_append f64array_append)
(define core_f64array_copy f64array_copy)
(define core_f64array_shrink f64array_shrink)
(define core_subf64array subf64array)
(define core_subf64array_fill subf64array_fill)
(define core_subf64array_move subf64array_move)

(define core_is_bit_array is_bit_array)
(define core_bit_array bit_array)
(define core_make_bit_array make_bit_array)
(define core_bit_array_length bit_array_length)
(define core_bit_array_set bit_array_set)
(define core_bit_array_is_set bit_array_is_set)
(define core_bit_array_is_all_set bit_array_is_all_set)
(define core_bit_array_is_any_set bit_array_is_any_set)
(define core_bit_array_clear bit_array_clear)
(define core_bit_array_set_all bit_array_set_all)
(define core_bit_array_clear_all bit_array_clear_all)
(define core_bit_array_to_list bit_array_to_list)
(define core_list_to_bit_array list_to_bit_array)
(define core_bit_array_to_string bit_array_to_string)
(define core_string_to_bit_array string_to_bit_array)
(define core_bit_array_is_eq bit_array_is_eq)
(define core_bit_array_blit bit_array_blit)
(define core_bit_arrays_concat bit_arrays_concat)
(define core_subbitarray subbitarray)
(define core_make_hashtable make_hashtable)
(define core_@ @)
(define core_make_eq_hashtable make_eq_hashtable)
(define core_make_equal_hashtable make_equal_hashtable)
(define core_is_hashtable is_hashtable)
(define core_eq_hash eq_hash)
(define core_eqv_hash eqv_hash)
(define core_equal_hash equal_hash)
(define core_string_hash string_hash)
(define core_symbol_hash symbol_hash)
(define core_string_ci_hash string_ci_hash)
(define core_hashtable_set hashtable_set)
(define core_hashtable_at hashtable_at)
(define core_hashtable_contains hashtable_contains)
(define core_hashtable_update hashtable_update)
(define core_hashtable_size hashtable_size)
(define core_hashtable_copy hashtable_copy)
(define core_hashtable_keys hashtable_keys)
(define core_hashtable_values hashtable_values)
(define core_hashtable_entries hashtable_entries)
(define core_hashtable_for_each hashtable_for_each)
(define core_transcoder transcoder)
(define core_transcoder_codec transcoder_codec)
(define core_transcoder_eol_style transcoder_eol_style)
(define core_transcoder_error_handling_mode transcoder_error_handling_mode)
(define core_file_reader file_reader)
(define core_file_writer file_writer)
(define core_file_stream file_stream)
(define core_current_reader current_reader)
(define core_current_writer current_writer)
(define core_current_error_stream current_error_stream)
(define core_byte_array_reader byte_array_reader)
(define core_byte_array_writer byte_array_writer)
(define core_get_output_bytes get_output_bytes)
(define core_string_reader string_reader)
(define core_string_writer string_writer)
(define core_get_output_string get_output_string)
(define core_pipe_reader pipe_reader)
(define core_pipe_writer pipe_writer)
(define core_pipe_stream pipe_stream)
(define core_pipe_process_pid pipe_process_pid)
(define core_pipe_process_status pipe_process_status)
(define core_tcp_server_stream tcp_server_stream)
(define core_tcp_client_stream tcp_client_stream)
(define core_is_stream is_stream)
(define core_is_writer is_writer)
(define core_is_reader is_reader)
(define core_close_stream close_stream)
(define core_close_writer close_writer)
(define core_close_reader close_reader)
(define core_stream_position stream_position)
(define core_stream_has_position stream_has_position)
(define core_set_stream_position set_stream_position)
(define core_call_with_stream call_with_stream)
(define core_is_eof_object is_eof_object)
(define core_eof_object eof_object)
(define core_read_byte read_byte)
(define core_read_n_bytes read_n_bytes)
(define core_read_all_bytes read_all_bytes)
(define core_read_char read_char)
(define core_peek_char peek_char)
(define core_read_n_chars read_n_chars)
(define core_read_all_chars read_all_chars)
(define core_read_line read_line)
(define core_read_all read_all)
(define core_read read)
(define core_write_byte write_byte)
(define core_write_n_bytes write_n_bytes)
(define core_write_char write_char)
(define core_write_chars write_chars)
(define core_write_n_chars write_n_chars)
(define core_show show)
(define core_showln showln)
(define core_newline newline)
(define core_write write)
(define core_flush_writer flush_writer)
(define core_reader_timeout reader_timeout)
(define core_writer_timeout writer_timeout)
(define core_stream_tokenizer stream_tokenizer)
(define core_get_token get_token)
(define core_peek_token peek_token)
(define core_is_keyword_token is_keyword_token)
(define core_is_special_token is_special_token)
(define core_special_token_to_string special_token_to_string)
(define core_expression expression)
(define core_statement statement)
(define core_slogan slogan)
(define core_current_task current_task)
(define core_is_task is_task)
(define core_task task)
(define core_root_task root_task)
(define core_task_run task_run)
(define core_task_yield task_yield)
(define core_task_sleep task_sleep)
(define core_task_terminate task_terminate)
(define core_task_join task_join)
(define core_task_name task_name)
(define core_task_set_data task_set_data)
(define core_task_data task_data)
(define core_task_set_base_priority task_set_base_priority)
(define core_task_base_priority task_base_priority)
(define core_task_set_priority_boost task_set_priority_boost)
(define core_task_priority_boost task_priority_boost)
(define core_task_base_priority task_base_priority)
(define core_task_set_quantum task_set_quantum)
(define core_task_quantum task_quantum)
(define core_task_send task_send)
(define core_task_receive task_receive)
(define core_task_messages_next task_messages_next)
(define core_task_messages_rewind task_messages_rewind)
(define core_task_state task_state)
(define core_task_state_is_uninitialized task_state_is_uninitialized)
(define core_task_state_is_initialized task_state_is_initialized)
(define core_task_state_is_active task_state_is_active)
(define core_task_state_active_waiting_for task_state_active_waiting_for)
(define core_task_state_active_timeout task_state_active_timeout)
(define core_task_state_is_normally_terminated task_state_is_normally_terminated)
(define core_task_state_normally_terminated_result task_state_normally_terminated_result)
(define core_task_state_is_abnormally_terminated task_state_is_abnormally_terminated)
(define core_task_state_abnormally_terminated_reason task_state_abnormally_terminated_reason)

(define core_task_group task_group)
(define core_is_task_group is_task_group)
(define core_task_group_name task_group_name)
(define core_task_group_parent task_group_parent)
(define core_task_group_resume task_group_resume)
(define core_task_group_suspend task_group_suspend)
(define core_task_group_terminate task_group_terminate)
(define core_mutex mutex)
(define core_is_mutex is_mutex)
(define core_mutex_name mutex_name)
(define core_mutex_set_data mutex_set_data)
(define core_mutex_data mutex_data)
(define core_mutex_state mutex_state)
(define core_mutex_lock mutex_lock)
(define core_mutex_unlock mutex_unlock)
(define core_monitor monitor)
(define core_is_monitor is_monitor)
(define core_monitor_name monitor_name)
(define core_monitor_set_data monitor_set_data)
(define core_monitor_data monitor_data)
(define core_monitor_notify monitor_notify)
(define core_monitor_broadcast monitor_broadcast)
(define core_rvar rvar)
(define core_rbind rbind)
(define core_rget rget)
(define core_process process)
(define core_process_send process_send)
(define core_process_receive process_receive)
(define core_process_close process_close)
(define core_spawn spawn)
(define core_current_directory current_directory)
(define core_path_expand path_expand)
(define core_path_normalize path_normalize)
(define core_path_extension path_extension)
(define core_path_strip_extension path_strip_extension)
(define core_path_directory path_directory)
(define core_path_strip_directory path_strip_directory)
(define core_path_strip_trailing_directory_separator path_strip_trailing_directory_separator)
(define core_path_volume path_volume)
(define core_path_strip_volume path_strip_volume)
(define core_create_directory create_directory)
(define core_create_link create_link)
(define core_create_symbolic_link create_symbolic_link)
(define core_rename_file rename_file)
(define core_copy_file copy_file)
(define core_delete_file delete_file)
(define core_delete_directory delete_directory)
(define core_list_directory list_directory)
(define core_file_exists file_exists)
(define core_file_info file_info)
(define core_is_file_info is_file_info)
(define core_file_info_type file_info_type)
(define core_file_info_device file_info_device)
(define core_file_info_inode file_info_inode)
(define core_file_info_mode file_info_mode)
(define core_file_info_number_of_links file_info_number_of_links)
(define core_file_info_owner file_info_owner)
(define core_file_info_group file_info_group)
(define core_file_info_size file_info_size)
(define core_file_info_last_access_time file_info_last_access_time)
(define core_file_info_last_modification_time file_info_last_modification_time)
(define core_file_info_last_change_time file_info_last_change_time)
(define core_file_info_creation_time file_info_creation_time)
(define core_file_info_attributes file_info_attributes)
(define core_file_type file_type)
(define core_file_device file_device)
(define core_file_inode file_inode)
(define core_file_mode file_mode)
(define core_file_number_of_links file_number_of_links)
(define core_file_owner file_owner)
(define core_file_group file_group)
(define core_file_size file_size)
(define core_file_last_access_time file_last_access_time)
(define core_file_last_modification_time file_last_modification_time)
(define core_file_last_change_time file_last_change_time)
(define core_file_creation_time file_creation_time)
(define core_file_attributes file_attributes)
(define core_os_name os_name)
(define core_host_name host_name)
(define core_host_info host_info)
(define core_is_host_info is_host_info)
(define core_host_info_name host_info_name)
(define core_host_info_aliases host_info_aliases)
(define core_host_info_addresses host_info_addresses)
(define core_shell_command shell_command)
(define core_exit exit)
(define core_command_line command_line)
(define core_getenv getenv)
(define core_setenv setenv)
(define core_compile compile)
(define core_load load)
(define core_reload reload)
(define core_link link)
(define core_now now)
(define core_is_time is_time)
(define core_time_to_seconds time_to_seconds)
(define core_seconds_to_time seconds_to_time)
(define core_time_second time_second)
(define core_time_minute time_minute)
(define core_time_hour time_hour)
(define core_time_day_of_month time_day_of_month)
(define core_time_month time_month)
(define core_time_day_of_week time_day_of_week)
(define core_time_day_of_year time_day_of_year)
(define core_time_set_second time_set_second)
(define core_time_set_minute time_set_minute)
(define core_time_set_hour time_set_hour)
(define core_time_set_day_of_month time_set_day_of_month)
(define core_time_set_month time_set_month)
(define core_time_set_day_of_week time_set_day_of_week)
(define core_time_set_day_of_year time_set_day_of_year)
(define core_time_is_dst time_is_dst)
(define core_time_set_is_dst time_set_is_dst)
(define core_process_times process_times)
(define core_real_time real_time)
(define core_cpu_time cpu_time)
(define core_current_exception_handler current_exception_handler)
(define core_set_current_exception_handler set_current_exception_handler)
(define core_raise raise)
(define core_is_noncontinuable_exception is_noncontinuable_exception)
(define core_noncontinuable_exception_reason noncontinuable_exception_reason)
(define core_show_exception show_exception)
(define core_error error)
(define core_is_error is_error)
(define core_error_message error_message)
(define core_error_args error_args)
(define core_c_struct_name c_struct_name)
(define core_c_struct_get c_struct_get)
(define core_c_struct_instance c_struct_instance)
(define core_pointer_to_c_struct pointer_to_c_struct)
(define core_ffi_open ffi_open)
(define core_ffi_close ffi_close)
(define core_ffi_fn ffi_fn)
(define core_ffi_call_void ffi_call_void)
(define core_ffi_call_void_pointer ffi_call_void_pointer)
(define core_ffi_call_char_string ffi_call_char_string)
(define core_ffi_call_int ffi_call_int)
(define core_ffi_call_uint ffi_call_uint)
(define core_ffi_call_int64 ffi_call_int64)
(define core_ffi_call_float ffi_call_float)
(define core_ffi_call_double ffi_call_double)
(define core_ffi_call_obj ffi_call_obj)
(define core_ffi_call_void_with_void_pointer ffi_call_void_with_void_pointer)
(define core_ffi_call_void_pointer_with_void_pointer ffi_call_void_pointer_with_void_pointer)
(define core_ffi_call_char_string_with_void_pointer ffi_call_char_string_with_void_pointer)
(define core_ffi_call_int_with_void_pointer ffi_call_int_with_void_pointer)
(define core_ffi_call_uint_with_void_pointer ffi_call_uint_with_void_pointer)
(define core_ffi_call_int64_with_void_pointer ffi_call_int64_with_void_pointer)
(define core_ffi_call_float_with_void_pointer ffi_call_float_with_void_pointer)
(define core_ffi_call_double_with_void_pointer ffi_call_double_with_void_pointer)
(define core_ffi_call_obj_with_void_pointer ffi_call_obj_with_void_pointer)
(define core_install_package install_package)
(define core_uninstall_package uninstall_package)
(define core_load_package load_package)

(define core_is_iterator is_iterator)
(define core_is_lpair is_lpair)
(define core_do_times do_times)
(define core_enable_asserts enable_asserts)

(namespace_create 'core '(compose identiy mapfn partial complement
                                  namespace_names namespace_hide namespace_unhide
                                  namespace_create namespace_delete apply until
                                  map for_each for_all exists fold_left fold_right
                                  fold callcc dynamic_wind values call_with_values
                                  force eval is_eq is_eqv is_equal is_boolean is_empty
                                  is_pair is_number is_complex is_real is_rational is_integer
                                  is_char is_string is_array is_u8array is_s8array is_bit_array
                                  is_symbol is_hashtable is_function pair head tail set_head
                                  set_tail list list_of is_list length at list_tail drop take
                                  take_while drop_while append reverse memq memv member memp
                                  remq remv remove remp filter partition sublist range find position
                                  assq assv assoc assp get copy_list zip zip_with sort quicksort
                                  mergesort first rest nth nth_tail second third fourth fifth sixth
                                  seventh eighth ninth tenth accumulate enumerate is_exact is_inexact
                                  number_is_eq number_is_lt number_is_gt number_is_lteq number_is_gteq
                                  add sub mult div inc dec is_zero is_positive is_negative is_even is_odd
                                  is_prime is_finite is_infinite is_nan quotient remainder modulo quo rem
                                  mod truncate floor ceiling round abs max min gcd lcm expt inexact exact
                                  rationalize numerator denominator rectangular polar real_part imag_part
                                  angle magnitude sqrt exp log logb sin cos tan asin acos atan bitwise_not
                                  bitwise_and bitwise_ior bitwise_xor bitwise_if bitwise_bit_count bitwise_length
                                  bitwise_first_bit_set bitwise_is_bit_set bitwise_is_any_bits_set bitwise_is_all_bits_set
                                  bitwise_copy_bit_field bitwise_arithmetic_shift bitwise_rotate_bit_field bitwise_reverse_bit_field
                                  string_to_number number_to_string is_fixnum least_fixnum greatest_fixnum fixnum_width
                                  fx_is_eq fx_is_lt fx_is_gt fx_is_lteq fx_is_gteq fx_is_zero fx_is_positive fx_is_negative
                                  fx_is_even fx_is_odd fxmin fxmax fxadd fxsub fxmult fxdiv fxmod fxadd_wrap fxsub_wrap
                                  fxmult_wrap fxnot fxand fxior fxxor fxif fxbit_count fxlength fxfirst_bit_set fxbit_is_set
                                  fxarithmetic_shift fxarithmetic_shift_left fxarithmetic_shift_right fxarithmetic_shift_wrap
                                  fxarithmetic_shift_left_wrap fxarithmetic_shift_right_wrap fxlogical_shift_right_wrap
                                  is_flonum fl_is_eq fl_is_lt fl_is_gt fl_is_lteq fl_is_gteq fl_is_zero fl_is_positive
                                  fl_is_negative fl_is_integer fl_is_finite fl_is_infinite fl_is_nan fl_is_even fl_is_odd
                                  flmin flmax fladd flsub flmult fldiv flmod flround fltruncate flfloor flceiling flnumerator
                                  fldenominator flabs flexp fllog fllogb flsin flcos fltan flasin flacos flatan flsqrt flexpt
                                  fixnum_to_flonum inf _inf nan zero _zero random_integer random_real random_byte_array
                                  default_random_source random_source is_random_source random_source_state random_source_set_state
                                  random_source_randomize random_source_pseudo_randomize random_source_for_integers random_source_for_reals
                                  random_source_for_byte_arrays char_is_eq char_is_lt char_is_gt char_is_lteq char_is_gteq char_is_ci_eq
                                  char_is_ci_lt char_is_ci_gt char_is_ci_lteq char_is_ci_gteq char_is_alphabetic char_is_numeric
                                  char_is_whitespace char_is_lower_case char_is_upper_case char_downcase char_upcase char_to_integer
                                  integer_to_char string_is_eq string_is_lt string_is_gt string_is_lteq string_is_gteq string_is_ci_eq
                                  string_is_ci_lt string_is_ci_gt string_is_ci_lteq string_is_ci_gteq string_starts_with string_ends_with
                                  string_ci_starts_with string_ci_ends_with string make_string string_length string_at string_set strings_at
                                  string_index_of string_replace_all string_copy string_append substring string_fill string_upcase
                                  string_downcase string_titlecase string_ltrim string_rtrim string_trim string_map string_for_each
                                  string_split strings_join string_to_list list_to_string string_to_u8array u8array_to_string
                                  string_to_symbol symbol_to_string gensym is_true is_false void is_void is_object array make_array
                                  array_length array_at arrays_at array_set array_fill array_to_list list_to_array array_copy
                                  array_append array_shrink subarray subarray_fill subarray_move array_sort array_map array_for_each
                                  u8array s8array make_u8array make_s8array u8array_length s8array_length u8array_to_bit_array
                                  u8array_at s8array_at u8array_set s8array_set u8array_to_list s8array_to_list list_to_u8array
                                  list_to_s8array object_to_u8array u8array_to_object u8array_fill s8array_fill u8array_append
                                  s8array_append u8array_copy s8array_copy u8array_shrink s8array_shrink subu8array subs8array
                                  subu8array_fill subs8array_fill subu8array_move subs8array_move is_bit_array bit_array make_bit_array
                                  bit_array_length bit_array_set bit_array_is_set bit_array_is_all_set bit_array_is_any_set bit_array_clear
                                  bit_array_set_all bit_array_clear_all bit_array_to_list list_to_bit_array bit_array_to_string string_to_bit_array
                                  bit_array_is_eq bit_array_blit bit_arrays_concat subbitarray make_hashtable make_eq_hashtable make_equal_hashtable
                                  is_hashtable eq_hash eqv_hash equal_hash string_hash symbol_hash string_ci_hash hashtable_set
                                  hashtable_at hashtable_contains hashtable_update hashtable_size hashtable_copy hashtable_keys hashtable_values
                                  hashtable_entries hashtable_for_each transcoder transcoder_codec transcoder_eol_style transcoder_error_handling_mode
                                  file_reader file_writer file_stream current_reader current_writer current_error_stream byte_array_reader
                                  byte_array_writer get_output_bytes string_reader string_writer get_output_string pipe_reader pipe_writer
                                  pipe_stream pipe_process_pid pipe_process_status tcp_server_stream tcp_client_stream is_stream
                                  is_writer is_reader close_stream close_writer close_reader stream_position stream_has_position
                                  set_stream_position call_with_stream is_eof_object eof_object read_byte read_n_bytes read_all_bytes
                                  read_char peek_char read_n_chars read_all_chars read_line read_all read write_byte write_n_bytes write_char
                                  write_chars write_n_chars show showln newline write flush_writer reader_timeout writer_timeout stream_tokenizer
                                  get_token peek_token is_keyword_token is_special_token special_token_to_string expression statement slogan
                                  current_task is_task task root_task task_run task_yield task_sleep task_terminate task_join task_name
                                  task_set_data task_data task_set_base_priority task_base_priority task_set_priority_boost task_priority_boost
                                  task_base_priority task_set_quantum task_quantum task_send task_receive task_messages_next task_messages_rewind
                                  task_state task_state_is_uninitialized task_state_is_initialized task_state_is_active task_state_active_waiting_for
                                  task_state_active_timeout task_state_is_normally_terminated task_state_normally_terminated_result
                                  task_state_is_abnormally_terminated task_state_abnormally_terminated_reason
                                  task_group is_task_group task_group_name task_group_parent task_group_resume task_group_suspend task_group_terminate
                                  mutex is_mutex mutex_name mutex_set_data mutex_data mutex_state mutex_lock mutex_unlock monitor is_monitor
                                  monitor_name monitor_set_data monitor_data monitor_notify monitor_broadcast rvar rbind rget process process_send
                                  process_receive process_close spawn current_directory path_expand path_normalize path_extension path_strip_extension
                                  path_directory path_strip_directory path_strip_trailing_directory_separator path_volume path_strip_volume
                                  create_directory create_link create_symbolic_link rename_file copy_file delete_file delete_directory list_directory
                                  file_exists file_info is_file_info file_info_type file_info_device file_info_inode file_info_mode
                                  file_info_number_of_links file_info_owner file_info_group file_info_size file_info_last_access_time
                                  file_info_last_modification_time file_info_last_change_time file_info_creation_time file_info_attributes
                                  file_type file_device file_inode file_mode file_number_of_links file_owner file_group file_size
                                  file_last_access_time file_last_modification_time file_last_change_time file_creation_time
                                  file_attributes os_name host_name host_info is_host_info host_info_name host_info_aliases host_info_addresses
                                  shell_command exit command_line getenv setenv compile load reload link now is_time time_to_seconds
                                  seconds_to_time time_second time_minute time_hour time_day_of_month time_month time_day_of_week
                                  time_day_of_year time_set_second time_set_minute time_set_hour time_set_day_of_month time_set_month
                                  time_set_day_of_week time_set_day_of_year time_is_dst time_set_is_dst process_times real_time cpu_time
                                  current_exception_handler set_current_exception_handler raise is_noncontinuable_exception
                                  noncontinuable_exception_reason show_exception error is_error error_message error_args c_struct_name
                                  c_struct_get c_struct_instance pointer_to_c_struct ffi_open ffi_close ffi_fn ffi_call_void ffi_call_void_pointer
                                  ffi_call_char_string ffi_call_int ffi_call_uint ffi_call_int64 ffi_call_float ffi_call_double ffi_call_obj
                                  ffi_call_void_with_void_pointer ffi_call_void_pointer_with_void_pointer ffi_call_char_string_with_void_pointer
                                  ffi_call_int_with_void_pointer ffi_call_uint_with_void_pointer ffi_call_int64_with_void_pointer
                                  ffi_call_float_with_void_pointer ffi_call_double_with_void_pointer ffi_call_obj_with_void_pointer
                                  install_package uninstall_package load_package is_s16array s16array make_s16array s16array_length s16array_at
                                  s16array_set s16array_to_list list_to_s16array s16array_fill
                                  s16array_append s16array_copy s16array_shrink subs16array
                                  subs16array_fill subs16array_move is_s32array s32array
                                  make_s32array s32array_length s32array_at s32array_set
                                  s32array_to_list list_to_s32array s32array_fill s32array_append
                                  s32array_copy s32array_shrink subs32array subs32array_fill subs32array_move
                                  is_u32array u32array make_u32array u32array_length u32array_at u32array_set
                                  u32array_to_list list_to_u32array u32array_fill u32array_append u32array_copy
                                  u32array_shrink subu32array subu32array_fill subu32array_move is_u16array
                                  u16array make_u16array u16array_length u16array_at u16array_set u16array_to_list
                                  list_to_u16array u16array_fill u16array_append u16array_copy u16array_shrink
                                  subu16array subu16array_fill subu16array_move is_s64array s64array make_s64array
                                  s64array_length s64array_at s64array_set s64array_to_list list_to_s64array
                                  s64array_fill s64array_append s64array_copy s64array_shrink subs64array
                                  subs64array_fill subs64array_move is_u64array u64array make_u64array
                                  u64array_length u64array_at u64array_set u64array_to_list list_to_u64array
                                  u64array_fill u64array_append u64array_copy u64array_shrink subu64array
                                  subu64array_fill subu64array_move is_f32array f32array make_f32array
                                  f32array_length f32array_at f32array_set f32array_to_list list_to_f32array
                                  f32array_fill f32array_append f32array_copy f32array_shrink subf32array
                                  subf32array_fill subf32array_move is_f64array f64array make_f64array
                                  f64array_length f64array_at f64array_set f64array_to_list list_to_f64array
                                  f64array_fill f64array_append f64array_copy f64array_shrink subf64array
                                  subf64array_fill subf64array_move is_iterator is_lpair do_times enable_asserts))

