#!/bin/bash

src_dir=$SLOGAN_ROOT/lib/crypto/c
src_files="$SLOGAN_ROOT/src/c/slogan.c $src_dir/huge.c $src_dir/des.c $src_dir/aes.c $src_dir/rsa.c"
incs="-I$SLOGAN_ROOT/src/include -I$SLOGAN_ROOT/platform/gsc/include -I$src_dir"
out_file=$src_dir/crypto.so
unamestr=`uname`

if [[ "$unamestr" == 'Darwin' ]]; then
    gcc -dynamiclib $incs -Wl,-undefined -Wl,dynamic_lookup -o $out_file $src_files
else # Linux and maybe BSDs?
    gcc -Wall -shared $incs -fPIC -o $out_file $src_files
fi

